### ISSUE TITLE
Jellybeans: low contrast white-on-blue in Normal mode

### ISSUE THREAD

**Issue by achilleas-k** [vim-airline/vim-airline-themes#10]
After the recent colour update for Jellybeans (PR #7), the blue colour on the status bar in Normal mode is too bright and it makes the white text have a very low contrast. The old blue was darker.

I do think the new blue looks better as part of the JB theme, but perhaps it would be nicer if the text `NORMAL` (and the right hand side part) was darker?

**Comment by mhartington** [comment]
Would you mind pulling down the latest bits, I just update the colors a bit. Should be close to the original but also make things a bit easier to read.

**Comment by achilleas-k** [comment]
The change must be very subtle, because for the life of me I can't actually **see** the difference, but it does seem that the contrast is better and the word NORMAL is easier to read now.

Either way, I'm happy with the change, whether it's actually more readable or not, so I'm closing the issue.

**Comment by pbogut** [comment]
It is much better now, thanks.
