### ISSUE TITLE
vim-airline disappeared in inactive window

### ISSUE THREAD

**Issue by j5shi** [vim-airline/vim-airline-themes#103]
I'm using the vim-airline theme `base16`, after a recent update of vim theme [gruvbox](https://github.com/morhetz/gruvbox), vim-airline disappeared in inactive windows (caused by incompatibility).

## Before:
![before](https://user-images.githubusercontent.com/6829121/29393744-3a858a52-8338-11e7-920a-9cf94a9b3191.png)

## After:
![after](https://user-images.githubusercontent.com/6829121/29393747-3e8f91b0-8338-11e7-95de-75c4f86613fe.png)

**Comment by chrisbra** [comment]
if gruvbox broke it, it should fix it.
