### ISSUE TITLE
Inactive airlines have wrong colour until vimrc sourced or terminal window resized

### ISSUE THREAD

**Issue by jplrssn** [vim-airline/vim-airline-themes#107]
Inactive airline bars (but not vertical window separators) blend into the background when creating new windows/splits. The colours are corrected by resizing the terminal window and by `:source ~/.vimrc`

Before sourcing vimrc:
![before](https://user-images.githubusercontent.com/2575219/29988781-eb77b10c-8f66-11e7-95ab-f9f2c8817a80.png)
After sourcing vimrc:
![after](https://user-images.githubusercontent.com/2575219/29988783-ed90794c-8f66-11e7-98b8-3077a72e3aac.png)

**Comment by chrisbra** [comment]
looks like some colors are not correctly setup. How to reproduce?

**Comment by chrisbra** [comment]
ping

**Comment by chrisbra** [comment]
closing as duplicate of #58
