### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by highvoltage** [vim-airline/vim-airline-themes#110]
Hi, thanks for this repository! I'm the packager for vim-airline-themes in Debian (which also makes its way to Ubuntu/Mint/etc). Would you consider tagging a release for this repository, and also for major updates like you do on the vim-airline repository? This will make it easier for me (and packagers of other systems) to ensure that we have the latest and greatest versions packaged. Thanks again!

**Comment by chrisbra** [comment]
duplicate #75. Will do that, once I release a new vim-airline version.

**Comment by highvoltage** [comment]
Thanks!
