### ISSUE TITLE
bubblegum theme isn't autodetected for bubblegum-256-dark colorscheme

### ISSUE THREAD

**Issue by sunaku** [vim-airline/vim-airline-themes#12]
Is there a precondition that a vim-airline theme name must _exactly_ match a colorscheme name in order for vim-airline to automatically detect the proper AirlineTheme to apply when `:colorscheme` is run? :partly_sunny:

In this case, the vim-airline theme name is "bubblegum" and the colorscheme name is "bubblegum-256-dark". :crossed_flags:

**Comment by chrisbra** [comment]
please update your airline plugin. It should then just work.

**Comment by sunaku** [comment]
Thanks, but it still didn't work :scream: because the colorscheme name is "bubblegum-256-dark", not simply "bubblegum". :fire:  In addition, the colorscheme comes with a light variant named "bubblegum-256-light" which should _also_ receive the same "bubblegum" Airline theme. :name_badge:

**Comment by chrisbra** [comment]
I did work for me, since obviously the colorscheme name matches bubblegum. Please check again.

**Comment by sunaku** [comment]
You're right! :sweat_smile: A leftover `let g:airline_theme` statement in my vimrc kept me from seeing the fix. :leaves: It all works correctly now, just as you said. :bow:
