### ISSUE TITLE
`g:airline_theme` does not work properly in neovim/vimR

### ISSUE THREAD

**Issue by fanzeyi** [vim-airline/vim-airline-themes#124]
I met this issue when I'm trying to migrate from vim to neovim (vimR), and it seems to me the option `g:airline_theme` is breaking.

If I set `g:airline_theme` to `hybrid` in my `init.vim`, airline will be displayed like this:

![screenshot 2018-02-01 13 02 41](https://user-images.githubusercontent.com/409951/35703239-48b67d24-0750-11e8-9638-118a8c3de78e.png)

and, if I set `g:airline_theme` to other themes - for example, `light` - the arrow won't be displayed properly. 

![screenshot 2018-02-01 13 04 25](https://user-images.githubusercontent.com/409951/35703315-7d2a567a-0750-11e8-8e6d-8d4e02fc2461.png)

However, if I leave it blank, it will use the default theme and works perfectly. I can also change the theme using `AirlineTheme` command.

![screenshot 2018-02-01 13 02 47](https://user-images.githubusercontent.com/409951/35703336-8de20bc0-0750-11e8-88e4-e4b8328988b1.png)

After using `AirlineTheme`:

![screenshot 2018-02-01 13 05 39](https://user-images.githubusercontent.com/409951/35703372-a5f24978-0750-11e8-8f21-cb6256ab2de2.png)

This might be a bug in vimR or neovim, but I want to confirm with you guys before I ask them. Thanks!

My .vimrc are following:

```.vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/fanzeyi/.dein_neo/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/fanzeyi/.dein_neo')
  call dein#begin('/Users/fanzeyi/.dein_neo/')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/fanzeyi/.dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')

  " Colorscheme
  call dein#add('kristijanhusak/vim-hybrid-material')

  " Global
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')

  " You can specify revision/branch/tag.
  "call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

set number
set autoindent
set smartindent
set showmatch
set ruler
set incsearch
set softtabstop=2
set shiftwidth=2
set tabstop=2
set smarttab
set expandtab
set nobackup
set noswapfile
set modeline
set go=e
set cursorline
set cursorcolumn
set wmnu
set hlsearch
set foldlevelstart=20


" Airline
let g:airline_powerline_fonts = 1
"let g:airline_theme='light'


set background=dark
colo hybrid_material
set colorcolumn=100
```

:version  (sorry I wasn't able to copy the version output from vimR's window)

![screenshot 2018-02-01 13 11 03](https://user-images.githubusercontent.com/409951/35703584-6a96d4e2-0751-11e8-8220-fb2d541a61f3.png)

**Comment by fanzeyi** [comment]
Umm. Someone has created an issue about this already at vim-airline/vim-airline#1654.

**Comment by notaduck** [comment]
Did you get it to work? I opened an isue much like this but got refered to this one which is also closed. @fanzeyi

**Comment by fabriziobertoglio1987** [comment]
@kazukazuinaina could you please help me with this issue? Thanks a lot.. hopefully I'll get the chance to contribute one day :pray:

**Comment by kazukazuinaina** [comment]
@fabriziobertoglio1987 

> この問題を手伝ってくれませんか

There is too little information to help.
This is because we can't tell if it's a problem with your vimrc configuration or with vim-airline.

Please tell us the minimum configuration that will reproduce the problem (e.g. remove the description of unrelated plugins)
and create the issue according to issue_templete.

PS: It's working fine in my environment.

**Comment by fabriziobertoglio1987** [comment]
@kazukazuinaina thanks I solved the problem. I installed https://github.com/ap/vim-buftabline and disabled the 

```
" let g:airline#extensions#tabline#formatter = 'unique_tail'
" let g:airline#extensions#tabline#enabled = 1
```
thanksa lot :pray: :peace_symbol:
