### ISSUE TITLE
Wrong colors in airline text when in tmux

### ISSUE THREAD

**Issue by persep** [vim-airline/vim-airline-themes#129]
Hi,
when in terminal I have vim with gruvbox and the gruvbox airline both working ok:
![Imgur](https://i.imgur.com/7I8xNWy.jpg)

If I change to the wombat airline theme, for testing purposes, it also works ok:
![Imgur](https://i.imgur.com/9DD2mZs.jpg)

So the airline themes work fine in the terminal but if a open vim inside tmux I get a different color in the text from the vim status line. Look at the different color in the "NORMAL" text
![Imgur](https://imgur.com/AjInN9G.jpg)

And if a change to the wombat airline you can see the "NORMAL" text color is also lighter:
![Imgur](https://imgur.com/M4J8FKJ.jpg)

It happens to all the other airline themes like solarized for example.
I've tried this in vim 8-1605 and tmux 2.1 and 2.6. I've also tried with tmux in 256 and 24 bit colors and it doesn't make a difference. Vim colors schemes are ok in tmux but not the text color from the airline themes. My terminal is Ubuntu on windows.

My `.tmux.conf` file is:

    set -g default-terminal "tmux-256color"                                              
    # enable 24 bit support                                                              
    set -g terminal-overrides ',xterm-256color:Tc'

**Comment by persep** [comment]
Opened it in the wrong repo. I'm closing it and opening it in vim-airline

**Comment by chrisbra** [comment]
For people coming here, the problem is in WSL Microsoft/console#136
