### ISSUE TITLE
Molokai theme change is unfitting

### ISSUE THREAD

**Issue by ElArtista** [vim-airline/vim-airline-themes#132]
Latest molokai theme change here: https://github.com/vim-airline/vim-airline-themes/pull/131, replaced the black portions on the bar with a bright orange, that not only seems unfitting due to being an 'alive/bright' color in the middle of 'pal' colors, but also makes that portion unreadable, considering the foreground is bright white.
I've been using this theme with heavy programming for at least the past two years, with an 256 color terminal set in molokai theme, and i can assure you this kind of bright color just hits the eye too hard.

I propose that the above theme is reverted.

**Comment by TheCrafter** [comment]
+1

**Comment by chrisbra** [comment]
cc @mimadrid for comment. I personally like the orange better, but don't use that theme, so my opinion does not matter much. In any case if you want to revert, please add a configuration variable and document it. thanks.

**Comment by mimadrid** [comment]
@ElArtista, @TheCrafter  What do you think about orange(172) and black letters?

![screenshot from 2018-03-31 17-11-28](https://user-images.githubusercontent.com/3269878/38164543-a9cbb4ba-3506-11e8-9ee2-d070d82c77ba.png)

**Comment by ElArtista** [comment]
Its a bad practice to choose the common 'error/warning' pop colors on status elements like this bar.
The mind is bound to think that something wrong happened to get this color.

For example take the trailing whitespace warning on the bar:
(No whitespace)
![image](https://user-images.githubusercontent.com/4622346/38172631-6efe353a-35b8-11e8-9ce3-33599a4d399d.png)
(With trailing whitespace)
![image](https://user-images.githubusercontent.com/4622346/38172641-aab08290-35b8-11e8-8b4b-5b9563f57f4e.png)

So far, i knew without reading the bar that if i saw something orange on bottom, then something wrong was happening (most commonly it being the trailing whitespace). Now i kinda get this feeling all the time.
