### ISSUE TITLE
base16-nord is missing

### ISSUE THREAD

**Issue by nwallace** [vim-airline/vim-airline-themes#133]
Hey -- I like the base16-nord colorscheme, but it's missing here. Is it possible to update the base16 schemes and get that one in?

**Comment by chrisbra** [comment]
IIRC, the base16 colorschemes were generated by somebody. If someone finds a way to create a new base16-nord theme, I'll gladly import it.

**Comment by chrisbra** [comment]
closing this. If someone wants additional themes, please create a PR with it.

**Comment by chrisbra** [comment]
care to create a proper PR for it?

**Comment by chrisbra** [comment]
I included it. However I needed to fix the palette name. Previously it was called base16-google. Now it is called base16_nord which should be the expected name. Please test. Thanks.
