### ISSUE TITLE
Cannot add the 'minimalist' theme

### ISSUE THREAD

**Issue by sahibjotsaggu** [vim-airline/vim-airline-themes#134]
I did tried `let g:airline_theme='minimalist'` and `:AirlineTheme minimalist` but I keep getting `The specified theme cannot be found.`

**Comment by chrisbra** [comment]
do you have it actually installed?

**Comment by sahibjotsaggu** [comment]
I have these inside my .vimrc:
```
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
```
I'm not sure what else I need to have installed.

**Comment by chrisbra** [comment]
and in your checked out version of vim-airline-themes there is a file `/autoload/airline/themes/minimalist.vim`?

**Comment by sahibjotsaggu** [comment]
Having that file in there would probably help eh?

When I installed vim-airline-themes, I assumed all the themes would be there.

Thanks a lot!

**Comment by chrisbra** [comment]
well yes, it should be there once you checked out the repository. Don't know how that file can be missing.
