### ISSUE TITLE
Themes not working in Neovim

### ISSUE THREAD

**Issue by still-dreaming-1** [vim-airline/vim-airline-themes#14]
I have both vim-airline and vim-airline-themes installed. After switching to Neovim, it still honors the original theme I had selected, but if I change to a different theme, I see this error message: 

> Could not resolve airline theme "base16_solarized.vim". Themes have been migrated to github.com/vim-airline/vim-airline-themes.

In case you are wondering, yes I did reinstall both plugins under the Neovim config directory. I used Plug to install them both.

**Comment by mhartington** [comment]
Hmm, I use neovim daily and haven't come across. Simple sanity test, could you delete the directories and reinstall the plugins?

**Comment by chrisbra** [comment]
And it works in Vim but not in Neovim? Perhaps you need to clone the directories to a different place for Neovim then?

**Comment by still-dreaming-1** [comment]
@mhartington Good idea. I will do that right now. @chrisbra My Neovim files are completely separate from my Vim files.

**Comment by still-dreaming-1** [comment]
Ahh, nevermind PEBCAK error. I was pasting file names into my theme, and was accidentally including the .vim part of the filename. This is the second time I have caught myself doing that. To prevent this from happening again, is there a command to show a list of supported themes, so I don't have to reference the filenames? Actually that would be much more convenient as well.
