### ISSUE TITLE
airline themes not work on tabline

### ISSUE THREAD

**Issue by pingsoli** [vim-airline/vim-airline-themes#142]
I have no idea what's is going on ? maybe the settings are misconfigured.

```
set background=dark
set t_Co=256

let g:airline#extensions#whitespace#enables = 0

" tabline settings
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#enable = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#tab_nr_type = 1 " tab number
let g:airline#extensions#tabline#tab_min_count = 2
let g:airline_theme='molokai'

let g:airline#extensions#default#layout = [
  \ [ 'a', 'b', 'c' ],
  \ [ 'z', 'error', 'warning' ]
  \ ]
```
![2018-06-11_102331](https://user-images.githubusercontent.com/15207838/41210061-e167b912-6d61-11e8-9131-9ee28efc7280.jpg)

please give me some advice, thanks a lot.

**Comment by pingsoli** [comment]
@bling 
how can I configure the settings and make my vim look like this. Please give me some advice, thank you.

![gif](https://camo.githubusercontent.com/ba79534309330accd776a8d2a0712f7c4037d7f9/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3330363530322f313037323632332f34346332393261302d313439352d313165332d396365362d6463616461336631633533362e676966)

**Comment by chrisbra** [comment]
what is the output of `:echo &tabline?`

**Comment by pingsoli** [comment]
appreciate your reply. @chrisbra 
```
E15: Invalid expression:          
E15: Invalid expression: &tabline?
```
`let g:airline#extensions#tabline#enable = 1` will load the tabline extensions, right ?

I check the  `vim --startuptime startup.log` and find the tabline extensions didn't load.

What's the problem ?

**Comment by chrisbra** [comment]
leave the question mark away. or use `:verbose set tabline? `

**Comment by pingsoli** [comment]
`:verbose set tabline?` just show:
```
tabline=
```

**Comment by pingsoli** [comment]
my bad.     thanks a lot.
