### ISSUE TITLE
How to customize a theme?

### ISSUE THREAD

**Issue by PaBLoX-CL** [vim-airline/vim-airline-themes#15]
I found that only a couple of colors doesn't suit my taste, but I can't found any documentation about just changing one or two colors.

Judging by the screenshots, in my laptop the bubblegum airline theme looks brighter.

**Comment by bling** [comment]
see the documentation for `g:airline_theme_patch_func ` here: https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L91

**Comment by Myzel394** [comment]
Here's the new link for 2023: https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L172

**Comment by chrisbra** [comment]
You could use a permalink, that would not point to master (to whatever specific commit that resolves), but just point to a very specific commit, like this one in 2023:

https://github.com/vim-airline/vim-airline/blob/3b9e149e19ed58dee66e4842626751e329e1bd96/doc/airline.txt#L172

**Comment by Myzel394** [comment]
That'll work, but I personally prefer to use those "failing" links (failing as in they will be outdated), because this way a user will immediately check that they are outdated :D and will (hopefully) search for the newest content
