### ISSUE TITLE
Base16 theme changes command completion menu color after writing to files in Neovim

### ISSUE THREAD

**Issue by jyzeng17** [vim-airline/vim-airline-themes#158]
OS: Ubuntu 16.04
Neovim: 0.3.0

I'm not sure if I should post it here, but it does not seem normal.

![test](https://user-images.githubusercontent.com/35042165/47364080-faabad80-d70a-11e8-9986-4964004e80f9.gif)

**Comment by jyzeng17** [comment]
Btw I've tried other themes and they don't have this problem.

**Comment by chrisbra** [comment]
The problem is the statusline highlighting?

**Comment by chrisbra** [comment]
what base16 theme did you use?

**Comment by jyzeng17** [comment]
Yeah the whole statusline is hightlighted when I press `<Tab>` to call the command completion menu, The appearances before and after I write something to the file are different.
I set `let g:airline_theme='base16'` in my startup vim script.

**Comment by chrisbra** [comment]
I just tried in a standard Vim:
![grafik](https://user-images.githubusercontent.com/244927/47409728-eba51980-d763-11e8-8ee9-4c4cc54c0602.png)

What is your output of `:hi WildMenu`. Mine is

    WildMenu       xxx term=standout cterm=bold ctermfg=161 ctermbg=237 gui=bold
                   guifg=#df005f guibg=#3a3a3a

Please also check with a standard Vim installation.

**Comment by chrisbra** [comment]
Also please check if the 'termguicolors' setting changes anything

**Comment by chrisbra** [comment]
And finally, what colorscheme are you using? Try this: `:verbose :hi WildMenu`

**Comment by jyzeng17** [comment]
I tested in my Vim and I found it behaves exactly as my Neovim does. Also I noticed that whether I start Vim with files argument or not will lead to different changes of my wildmenu color. I didn't set 'termguicolors' and I used gruvbox colorscheme when I tested, I'm not sure if this affects the result so I also tested with no colorscheme set.

* Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm
```

* Open no file with no colorscheme: works normally
* Open no file with gruvbox colorscheme:
![3](https://user-images.githubusercontent.com/35042165/47427183-2fc70700-d7c2-11e8-92a9-bc85a41b3952.gif)
```
WildMenu       xxx term=standout cterm=bold ctermfg=109 ctermbg=239 gui=bold
                   guifg=#83a598 guibg=#504945
        Last set from ~/.vim/bundle/gruvbox/colors/gruvbox.vim
```
* Open files with no colorscheme:
![2](https://user-images.githubusercontent.com/35042165/47427224-4d946c00-d7c2-11e8-8032-f4ca9fe67f90.gif)
```
WildMenu       xxx term=standout ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
```
* Open files with gruvbox colorscheme:
![1](https://user-images.githubusercontent.com/35042165/47427236-54bb7a00-d7c2-11e8-8502-d2e6489aba8b.gif)
```
WildMenu       xxx term=standout cterm=bold ctermfg=109 ctermbg=239 gui=bold
                   guifg=#83a598 guibg=#504945
        Last set from ~/.vim/bundle/gruvbox/colors/gruvbox.vim
```

**Comment by chrisbra** [comment]
hm, perhaps your terminal does not show more than 16 colors? Does `:set t_Co=256` fix it?

**Comment by chrisbra** [comment]
Btw what terminal is this? When that happens (and the output is unreadable), what is the output of `:hi WildMenu` and `:hi StatusLine`?

**Comment by jyzeng17** [comment]
My terminal is GNOME Terminal 3.18.3. `:set t_Co=256` didn't fix it.

If I open a file with no colorscheme, the output of `:hi WildMenu` after color changing:
```
WildMenu       xxx term=standout ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
```
And the output of `:hi StatusLine` in the same condition:
```
StatusLine     xxx term=bold,reverse cterm=bold,reverse ctermfg=130 gui=bold,reverse
```

![11111](https://user-images.githubusercontent.com/35042165/47431622-d5807300-d7ce-11e8-9b8f-fd0578cff903.png)

**Comment by chrisbra** [comment]
I am struggeling a bit with following your conversation. That looks like the contrast between those two highlighting groups should be okay, so the problem mentioned in the first message should not show up in this circumstance, right? Or is this when the completion (wildmenu mode) is almost invisible?

**Comment by jyzeng17** [comment]
Well I think my problem now is that my wildmenu will automatically change its color right after I write something to the file. The first message is just it happened to change its color to one that looks like invisible (I guess it's because of my gruvbox colorscheme setting, so I remove the setting for my last comment. And the problem exists still, just switch to another color). Here's the highlighting groups output for my first message's situation:
![123](https://user-images.githubusercontent.com/35042165/47439437-f51f9780-d7de-11e8-9fd3-e2004a02cdab.png)

**Comment by chrisbra** [comment]
Hm, it looks like the Statusline highlighting group is wrong at least for the terminal. See how `ctermfg` equals `ctermbg` (this means the foreground color is the same as the background color for the terminal, note that you cannot see the `xxx` that should be present)?

Does this come from the gruvbox color scheme? Check `:verbose :hi StatusLine`. If that comes from gruvbox, I suggest filing an issue there.

**Comment by jyzeng17** [comment]
![123456](https://user-images.githubusercontent.com/35042165/47468021-a8ae7900-d82b-11e8-976c-73d93971ad6a.png)

Looks like it's from vim-airline.

**Comment by chrisbra** [comment]
Now that is interesting. Ah found the problem and fixed it.

**Comment by jyzeng17** [comment]
That solves the problem! Thank you.
