### ISSUE TITLE
powerlineish theme doesn't change right side's color

### ISSUE THREAD

**Issue by LunarLambda** [vim-airline/vim-airline-themes#159]
Insert mode is correct, but Visual and Replace modes are not:
![image](https://user-images.githubusercontent.com/38919842/48021497-149cb580-e139-11e8-8981-f76a6041d68e.png)
![image](https://user-images.githubusercontent.com/38919842/48021482-0a7ab700-e139-11e8-91ef-8205143cc15c.png)
![image](https://user-images.githubusercontent.com/38919842/48021488-0ea6d480-e139-11e8-97ee-321282b33eb6.png)

**Comment by chrisbra** [comment]
What should they Look like?

**Comment by LunarLambda** [comment]
I feel the color on the right side (<100% ...) should match the one the left

Orange/Black for Visual and Select modes
Red/White for Replace

**Comment by LunarLambda** [comment]
Will do when I can, thanks
