### ISSUE TITLE
Lucius theme does not highlight current tab

### ISSUE THREAD

**Issue by etanol** [vim-airline/vim-airline-themes#16]
After upgrading *vim-airline* to vim-airline@e6ab7bdf6d2f906ecf292268785f80da36e49cba, the Lucius theme stopped highlighting the active tab:

![screenshot](https://cloud.githubusercontent.com/assets/85804/13216655/627d5e12-d95d-11e5-9238-c123e7254014.png)

**Comment by etanol** [comment]
After bisecting *vim-airline*, looks like the problem originates [in this commit](https://github.com/vim-airline/vim-airline/commit/2c5aa75d5fdf4dd462a0ee55c2e66e852b17260c).

**Comment by chrisbra** [comment]
Can you check, if this patch fixes it for you?
```patch
diff --git a/autoload/airline/themes/lucius.vim b/autoload/airline/themes/lucius.vim
index e386900..fa89a87 100644
--- a/autoload/airline/themes/lucius.vim
+++ b/autoload/airline/themes/lucius.vim
@@ -40,7 +40,7 @@ function! airline#themes#lucius#refresh()
     let g:airline#themes#lucius#palette.visual.airline_warning = g:airline#themes#lucius#palette.normal.airline_warning
     let g:airline#themes#lucius#palette.visual_modified.airline_warning = g:airline#themes#lucius#palette.normal_modified.airline_warning

-    let s:IA = airline#themes#get_highlight('StatusLineNC')
+    let s:IA = airline#themes#get_highlight('Tabline')
     let g:airline#themes#lucius#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA, s:IA)
     let g:airline#themes#lucius#palette.inactive_modified = {
                 \ 'airline_c': [ modified_group[0], '', modified_group[2], '', '' ]
```

**Comment by etanol** [comment]
Not really, although there is a slight difference.  This is the unpatched tabline:

![unpatched](https://cloud.githubusercontent.com/assets/85804/13220908/f37838e0-d978-11e5-83c7-e8b5d809b6de.png)

And this is with your proposed change:

![patched](https://cloud.githubusercontent.com/assets/85804/13220910/fb4d8e4e-d978-11e5-9218-f2d70158822d.png)

Note the vertical bar between the two captions.

**Comment by chrisbra** [comment]
What terminal is this and what are your color settings? I cannot reproduce this, it looks like you do not have 256color mode enabled?

**Comment by etanol** [comment]
The screenshots are from GTK Vim on Ubuntu 14.04, so the color palette should be larger than 256.

**Comment by rosston** [comment]
I have a similar problem caused by the same PR (vim-airline/vim-airline#952; I narrowed it down to vim-airline/vim-airline@e4ef624). I use the dark theme, and that commit causes the buffer to incorrectly appear modified (blue) after 1) opening the file from within vim, or 2) modifying and then saving the buffer.

I've reproduced the problem in Neovim (0.1.2), MacVim (7.4p1265), and Vim (7.4p1265).

**Comment by rosston** [comment]
I'm not sure how helpful this is, but reverting _just_ the changes in `autoload/airline/extensions/tabline/buffers.vim` (https://github.com/vim-airline/vim-airline/commit/e4ef624#diff-08d733ab4d38041892b71b200ba7fec6L65) fixes the problem for me. I left the rest of the commit's changes intact, and reverted only the changes in `buffers.vim`.
