### ISSUE TITLE
[Feature Request] Support random theme

### ISSUE THREAD

**Issue by voldikss** [vim-airline/vim-airline-themes#170]
Will airline support random theme like `ZSH_THEME=random` in [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/)?

Every time after Vim started, selecting a random them for users is quite interesting.

I've something like this in my `vimrc` and it works
```vim
function! Randnum(max) abort
  return str2nr(matchstr(reltimestr(reltime()), '\v\.@<=\d+')[1:]) % a:max
endfunction

let g:airline_themes_list = ['aurora', 'base16_spacemacs', 'cool', 'light', 'vice']
let g:randomn = Randnum(len(g:airline_themes_list))

if expand("%:t") == '.vimrc' && expand("%:p:h") ==# expand("~")
    exec "AirlineTheme " . g:airline_themes_list[g:randomn]
else
    let g:airline_theme = g:airline_themes_list[g:randomn]
endif
```
But I hope that it will be built in this plugin

**Comment by chrisbra** [comment]
you mean having a special theme `random`, that does perform something like your snippet above?

**Comment by voldikss** [comment]
Yes.

When I set the theme name as "random", the plug-in will pick a random theme for me:

```vim
let g:airline_theme='random'
```

**Comment by voldikss** [comment]
Thanks very much! 

It has an error when I source `$MYVIMRC`, and I issued it [here](https://github.com/vim-airline/vim-airline/issues/1891)
