### ISSUE TITLE
Improve the text color for diagnostics (coc and ale) in base 16

### ISSUE THREAD

**Issue by jethrosun** [vim-airline/vim-airline-themes#173]
<img width="667" alt="Screen Shot 2019-05-03 at 3 31 34 PM" src="https://user-images.githubusercontent.com/15823053/57161109-b5062680-6db8-11e9-9063-2309c5181bd0.png">

Like what is shown in the screenshot, currently the text color is not very distinguishable from the orange background for some base 16 themes ( the one I am using is base 16 atelierdune). How can we improve this? I have played with the config but no luck.

Edited:
<img width="675" alt="Screen Shot 2019-05-03 at 4 00 47 PM" src="https://user-images.githubusercontent.com/15823053/57162580-a6217300-6dbc-11e9-96c9-370930674a99.png">

**Comment by chrisbra** [comment]
I guess the `airline_warning` and `airline_error` sections could need some tweaks.

**Comment by jethrosun** [comment]
Yeah that is right. Turns out not every theme set up the warning and error color explicitly so the default one is kind of ugly and hard to read. I copy the part from dracula and now the base16 atelierdune works fine (see [here](https://github.com/jethrosun/vim-airline-themes/blob/master/autoload/airline/themes/base16_atelierdune.vim#L68) ). Do you think I should push a PR for base16 atelierdune?
<img width="1652" alt="Screen Shot 2019-05-06 at 10 45 42 AM" src="https://user-images.githubusercontent.com/15823053/57233172-1f52dd00-6fec-11e9-9681-97d67838e5ad.png">

**Comment by chrisbra** [comment]
sure go ahead please.
