### ISSUE TITLE
The colors in terminal.app and iterm2 are very different for the same theme.

### ISSUE THREAD

**Issue by xianyinxin** [vim-airline/vim-airline-themes#177]
I set the airline and airline-theme for vim properly, but i found the color ouputs are very differently in terminal.app and iterm2.

I use solarized light for iterm2, terminal.app and the air-line theme.

It seems iterm2 gives similar outputs as the screenshots of the wiki, but in terminal.app, the colors are strange: in normal mode, the backgroud is yellow which the words "NORMAL" is white, so it's hard to see it clear.

**Comment by xianyinxin** [comment]
<img width="1312" alt="abnormal_color_in_terminal_osx" src="https://user-images.githubusercontent.com/15028683/58372148-2c5c4f80-7f4c-11e9-93e0-0f89bece1c43.png">
A screenshot for contrast

**Comment by chrisbra** [comment]
Most likely a configuration issue. Probably depends on `termguicolors` and the `t_Co` setting.
