### ISSUE TITLE
base16_spacemacs not working properly

### ISSUE THREAD

**Issue by welblaud** [vim-airline/vim-airline-themes#183]
In Vim inside terminal, this theme looks (in gVim it looks great):
![obrazek](https://user-images.githubusercontent.com/8298610/63496854-e9663580-c4c2-11e9-9faa-3783f1e60f97.png)

- temirnal 3.32.1-1ubuntu1
- bash 5.0.3
- Ubuntu 19.04

It seems many Vim themes have problems with terminal themes, which sometimes override Vim themes' colors. Switching to another terminal theme does not help. The airline theme is always a bit distorted according to the terminal's theme.

**Comment by chrisbra** [comment]
Most of the base16 themes have been generated and work best for the gui or when termguicolors is set. I don't use base16 and cannot create proper terminal support (I am not very good in graphical things), therefore I depend on the help of the community. So PRs welcome.
