### ISSUE TITLE
How should I override theme colors?

### ISSUE THREAD

**Issue by bergentroll** [vim-airline/vim-airline-themes#184]
I am on nvim with jellybean them. I trying to override bg color of airline_c to visually split vertical stack of windows. I have no luck with `hi airline_c ctermbg=0`. I also suppose, that I should do `let g:airline#somevariable=...`, but I have no point what exactly.

Sorry for such question in issues. :pray:

**Comment by chrisbra** [comment]
you probably want to adjust the jellybean theme and adjust the colors mentioned there.
