### ISSUE TITLE
Dracula inactive theme has only two colors

### ISSUE THREAD

**Issue by andys8** [vim-airline/vim-airline-themes#191]
Dracula theme looks like this to me, if the buffer is inactive. I'm not sure if it's intended to look like this

![image](https://user-images.githubusercontent.com/13085980/69501573-711a7080-0f06-11ea-90ba-d10c11594674.png)

I played around with some colors and having at least some separation would be nice:
![image](https://user-images.githubusercontent.com/13085980/69501598-ac1ca400-0f06-11ea-8420-0a21cb8ec0f6.png)

https://github.com/vim-airline/vim-airline-themes/blob/ad6cc5261bff23a5b8d7232a971881f79909e767/autoload/airline/themes/dracula.vim#L71

**Comment by chrisbra** [comment]
it's inactive, so I would say this is intended.

**Comment by chrisbra** [comment]
BTW: feel free to add an option and create a PR for this (don't forget to document the option then).

**Comment by kazukazuinaina** [comment]
What do you think this patch? @chrisbra 
```diff
-let g:airline#themes#dracula#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA, s:IA)
+
+if get(g:, 'airline#themes#dracula#inactive_simple', 1)
+  let g:airline#themes#dracula#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA, s:IA)
+else
+  let g:airline#themes#dracula#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN2, s:IA)
+endif
```

**Comment by kazukazuinaina** [comment]
@andys8 
I will try to create Pull request.
Is it OK?

**Comment by andys8** [comment]
@kazukazuinaina Of course, thanks a lot!

@chrisbra I tried some other themes and their inactive versions have (decent) colors. But Dracula currently has a single text and a single background color. I initially guessed `vim-airline` might be broken. I think the colors can be improved, and I'm fine with it, but in my opinion the flag/option might not be necessary.

**Comment by kazukazuinaina** [comment]
Okey! I will create Pull Request!

@andys8 and @chrisbra 
I think it's a good thing to have many choices, what do you think?

**Comment by chrisbra** [comment]
It's a matter of taste and it seems like the current behavior was intended by the author @joaovinicius 

The question I have currently is:
- if we change the current behaviour, will anybody complain because they want the current behaviour?

We had too many complaints in the past, therefore, I'll accept only changes if they are documented and are configurable (unless it is clearly a bug or several people agree)

- What change would fit to the current dracula colorscheme? Does the proposed change fit to the intention of the dracula authors? CC'ing @joaovinicius @dsifford and @benknoble for opinions.

Either way, I don't mind too much and I am fine with changing it but since I am not good at graphics, I'd like to hear more opinions.

**Comment by kazukazuinaina** [comment]
Thanks. @chrisbra 
I look forward to solving this problem in a better direction.

**Comment by benknoble** [comment]
I stopped using Airline some time ago... FWIW, my custom statusline makes use of dracula colors, but just uses bold/no-bold to highlight the active window (though I may revisit that).

The best place to check out "dracula colorscheme vim stuff" is the https://github.com/dracula/vim repo—also see https://dsifford.github.io/dracula-spec/

**Comment by chrisbra** [comment]
@benknoble  thanks. I don't know if the suggested edit makes sense and fits the colorscheme.

@andys8 Can you please give feedback #192? thanks.

**Comment by andys8** [comment]
The PR is exactly using the colors I had, when playing around and creating the first screenshot(`s:IN1, s:IN2, s:IA`). I don't have an idea how they were initially meant. As long as the PR is working it looks fine to me and I'd be happy to use it.

**Comment by dsifford** [comment]
So just chiming in with an observation. I haven't really dug into this issue thread all that hard, but I'm curious about this... Why does the airline repo also have a dracula configuration when [we maintain one ourselves](https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim)? Could this cause inconsistency issues? Ping @chrisbra

**Comment by chrisbra** [comment]
@dsifford no, because what airline provides is just a way to style the different parts of your statusline. Those should obviously match the global colorscheme, that's why we call those here `themes` and they only cover how the different parts in the statusline are colored.

**Comment by chrisbra** [comment]
oh, wait a second. So the dracula colorscheme already comes with a airline theme. Then we should indeed drop this one

**Comment by chrisbra** [comment]
I dropped this scheme. @andys8  please report your issue upstream then.

**Comment by andys8** [comment]
Mhh, gonna have to try it. But: I'm using https://github.com/flazz/vim-colorschemes/blob/master/colors/dracula.vim instead of `dracula/vim`.

**Comment by dsifford** [comment]
Try the official one. You might be pleasantly surprised. 👍

**Comment by andys8** [comment]
I'll try again. I tried it multiple times and the result in syntax hightlighting was worse (opinion, of course).

**Comment by chrisbra** [comment]
I agree, if possible, always try the upstream repository. Chances are, they can fix your problems early. 

BTW: This was also the reason, I have never merged the various include a gruvbox airline theme PRs.

**Comment by andys8** [comment]
@dsifford Left `dracula/vim`, right `vim-colorschemes`.
![image](https://user-images.githubusercontent.com/13085980/69725648-e52f6100-111e-11ea-99c3-5d9008ec18ed.png)

**Comment by andys8** [comment]
And more relevant for the issue: Yes, they have airline styles. The inactive version looks like this:
![image](https://user-images.githubusercontent.com/13085980/69725756-35a6be80-111f-11ea-96af-d6104808efdd.png)

**Comment by dsifford** [comment]
@andys8 Re: the first issue: That's because your terminal doesn't support full truecolor. So to achieve the proper colors on your degraded terminal, you should set `let g:dracula_colorterm = 0` and possible disable `termguicolors` if you have that enabled.

Re: the second one. Open an issue and we can talk about it there.

**Comment by kazukazuinaina** [comment]
@chrisbra 

Thanks for management

**Comment by kazukazuinaina** [comment]
@dsifford 

Thanks for giving suggestion!

**Comment by kazukazuinaina** [comment]
@chrisbra 

I thought this was a good decision.

It's a shame that my patch wasn't adopted, but it is my hope if vim-airline is going in a better direction.

Let me help vim-airline from now on!

**Comment by chrisbra** [comment]
@kazukazuinaina sorry, about that. But we really shouldn't diverge with different themes for the same colorscheme. Try proposing your patch to the dracula color scheme so it makes everybody happy 😄

**Comment by dsifford** [comment]
We're extremely open to PRs in the dracula repo so long as it conforms to the running spec (linked above by @benknoble ) and the dracula core scheme.

The sort of trickiness in maintaining a theme that is so widely used is that you have to force yourself to make decisions that don't stray too far from "sane" defaults. Lots of opinions out there and it's impossible to please everybody. If changes are proposed that stray a bit too far from our "sane default" philiosophy, we will generally tell the submitter to either add their proposed changes to their own `.vimrc` or to fork.

**Comment by andys8** [comment]
I changed my theme to `dracula/vim`. I disabled italics (has to happen before the theme is set) and `dracula_colorterm = 0` which results in a different background. The difference in syntax coloring was because of differences in `elm` syntax.

Regarding the vim-airline (the actual topic). It looks like this to me (`notermguicolors`).

#### left active, right inactive

![image](https://user-images.githubusercontent.com/13085980/69740431-abb81f00-1139-11ea-82a8-d303a4717bee.png)

**Comment by andys8** [comment]
How about this for inactive airlines?
![image](https://user-images.githubusercontent.com/13085980/69741449-57ae3a00-113b-11ea-9a75-cdcb19b41e8d.png)

**Comment by chrisbra** [comment]
please request upstream.

**Comment by andys8** [comment]
Question was targeted to @dsifford  but you're right.
