### ISSUE TITLE
aurora theme has overlapping color schemes across repositories.

### ISSUE THREAD

**Issue by kazukazuinaina** [vim-airline/vim-airline-themes#195]
Hi, Christian.

I think this is similar to the following problem #192 

Please look this repo.

> https://github.com/everard/vim-aurora/blob/master/vim-airline/autoload/airline/themes/aurora.vim

This color scheme overlaps with the above repository.

I can write a patch to reslove this problem, but I don't know which is the best choice.

Probably there are three options:

1. delete this theme from `vim-airline-themes`'s repo
2. delete this theme from `vim-aurora`'s repo
3. keep

I want to hear your opinion. @chrisbra @everard

**Comment by chrisbra** [comment]
we should remove the theme in that case.

**Comment by kazukazuinaina** [comment]
@chrisbra 
OK, I will create Pull Request to resolve this issue.
