### ISSUE TITLE
Saving a buffer doesn't remove highlight in the buffer line

### ISSUE THREAD

**Issue by megapctr** [vim-airline/vim-airline-themes#21]
I noticed that current buffer background in the buffer line is not updated after saving the buffer. Switching the buffer back and forth does update the color.

Some facts:
  - This happens only when at least two buffers are open
  - The issue was not present before splitting vim airline themes into a separate repo
  - I'm using base16-solarized theme, but I don't think this is the case

How to reproduce:
  1. Open two files. Current buffer has blue background.
  2. Modify the file. Current buffer has green background and a `+` after the filename
  3. Save the file. Current buffer background is still green, though it should go back to blue. The `+` is gone from the filename.
  4. Switch to next buffer and go back. Current buffer is blue, as it should be.

**Comment by chrisbra** [comment]
Are you talking about the tabline extension? If so, does vim-airline/vim-airline#1057 fix it for you?

**Comment by megapctr** [comment]
Yes! thanks :)
