### ISSUE TITLE
How to edit the hack airline colors ?

### ISSUE THREAD

**Issue by linxed** [vim-airline/vim-airline-themes#212]
I dont really have any issues with the ariline theme more lie request for assitance.

I've been playing around with iterm2 and this is what i ended up with 
<img width="1440" alt="Screen Shot 2020-02-16 at 11 28 31 PM" src="https://user-images.githubusercontent.com/58088514/74613091-10b95a80-5114-11ea-8440-324544d01cbc.png">
The issue is when i go in insert mode 
<img width="1440" alt="Screen Shot 2020-02-16 at 11 29 13 PM" src="https://user-images.githubusercontent.com/58088514/74613102-29c20b80-5114-11ea-8147-b28ac31fcd63.png">
What would like to know which variable should i edit in order to change that green color from the insert and the last part of the airline 
<img width="1440" alt="Screen Shot 2020-02-16 at 11 30 43 PM" src="https://user-images.githubusercontent.com/58088514/74613133-5e35c780-5114-11ea-9901-94e13889eb16.png">

**Comment by chrisbra** [comment]
edit the theme and look for `g:airline#themes#hybrid#palette.insert`

**Comment by linxed** [comment]
Thanks
