### ISSUE TITLE
Understanding the branch icons / information

### ISSUE THREAD

**Issue by FernandoBasso** [vim-airline/vim-airline-themes#215]
#### environment

- vim: 8.2 patches 1-510
- vim-airline: 0.10
- colorscheme: vim default theme
- OS: Arch Linux
- Have you reproduced with a minimal vimrc: No
- What is your airline configuration: default, with xtermlight Airline theme
- terminal: xfce4-terminal/tmux
- $TERM variable: screen-256color
- color configuration (:set t_Co?): 256

I am not being able to fully understand the meaning of the icon next to the branch name.

![commited-pushed](https://user-images.githubusercontent.com/6560620/79444048-03540b80-7fb1-11ea-8cdf-58f06501dfab.png)
![modified-files](https://user-images.githubusercontent.com/6560620/79444051-03eca200-7fb1-11ea-8ab0-a871d480b916.png)
![modified-files-2](https://user-images.githubusercontent.com/6560620/79444052-04853880-7fb1-11ea-97e2-d8872ebd30a9.png)

Sometimes there is no icon, sometimes that “lightening” icon, sometimes that icon similar to ∉. Is this something documented somewhere? If not, I'd like a brief explanation, if possible.

Thanks!

**Comment by chrisbra** [comment]
this issue actually belongs to the vim-airlines repository. Please have a look at the documentation:

From [https://github.com/vim-airline/vim-airline/blob/7c318503815316b78f10803d6b38ca1679128b46/doc/airline.txt#L346-L358]

>   let g:airline_symbols.notexists = 'Ɇ'
>   [...]
>   let g:airline_symbols.dirty='⚡'

the dirty symbol basically means your working directory is dirty (e.g. there are uncommited changes),
the notexists symbol means you are editing a file, that has not been commited yet.

Please suggest a documentation improvements. Thanks!

**Comment by kazukazuinaina** [comment]
I think it is vim-airline's issue.
Therefore, I thought it was better to transfer this issue to vim-airline's repo.
What do you think? @chrisbra

**Comment by chrisbra** [comment]
I think this can be closed, right?

**Comment by kazukazuinaina** [comment]
I agree with @chrisbra
