### ISSUE TITLE
Gaps between symbols in some themes

### ISSUE THREAD

**Issue by Mati20187** [vim-airline/vim-airline-themes#216]
#### environment

- vim: 8.2.717
- vim-airline: latest
- colorscheme: base16_gruvbox_dark_hard
- OS: Arch Linux
if you are using terminal:
- terminal: st
- $TERM variable: st-256color

#### actual behavior

In some of the provided colorschemes (I didn't check all of them but some of them are: alduin, base16_chalk, angr, base16_gruvbox_dark_hard, base16_apathy, base16_default etc.) there is a gap between symbols.

#### expected behavior

There should be no gap (there's no problem with themes like base16_adwaita, simple, base16_greenscreen etc.)

#### screen shot (if possible)

base16_gruvbox_dark_hard:
![gruv-dark](https://user-images.githubusercontent.com/31066931/81541387-8a06c900-9362-11ea-82a0-368b8b5bfc5b.png)

base16_adwaita (no issue here):
![adwaita](https://user-images.githubusercontent.com/31066931/81541538-c6d2c000-9362-11ea-9bff-6056c4ea8a79.png)

Can anyone check whether they have the same issue or is it just me?

**Comment by chrisbra** [comment]
could be font or terminal related problem. Nothing we can fix here.

**Comment by Mati20187** [comment]
Yeah, you were right. BitStream Vera Sans Mono is not supported. I changed the font to Hack and everything works fine
