### ISSUE TITLE
How to create/edit themes if not asking for a commit?

### ISSUE THREAD

**Issue by hrqmonteiro** [vim-airline/vim-airline-themes#219]
#### environment

- vim: nvim
- vim-airline: last version
- colorscheme: ?
- OS: Void
- Have you reproduced with a minimal vimrc: yes
- What is your airline configuration: default
if you are using terminal:
- terminal: alacritty
- $TERM variable: xterm-256color
- color configuration (:set t_Co?): 
if you are using Neovim:
- does it happen in Vim: don't know, don't use it

#### actual behavior

How to edit or create a theme? I try to edit a theme but no matter WHAT I DO, the colors remain the same. Same thing happen if a create a new theme.vim in the folder and try to set it. No changes happen, no matter what i change in the theme file.

#### expected behavior

Well i guess i expect to work the edits.

**Comment by chrisbra** [comment]
what have you tried?
Also have a look at the default theme. It contains some comments:
https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/themes/dark.vim

**Comment by hrqmonteiro** [comment]
> what have you tried?
> Also have a look at the default theme. It contains some comments:
> https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/themes/dark.vim

Well i tried to get a theme file on the folder and edit. And now i got the dark default theme and edited. I edited literally all the colors, and no change applies.

What am i missing, i mean what are the steps to edit a theme? (The dark, for example)

**Comment by chrisbra** [comment]
I would suggest to change the new name. Make sure to re-load the theme

**Comment by kazukazuinaina** [comment]
@hrqmonteiro 
No reply?
