### ISSUE TITLE
Wrong colors in base16_flat theme

### ISSUE THREAD

**Issue by Ch00k** [vim-airline/vim-airline-themes#22]
I noticed that 6d3710e completely changed the colors I used to have in base16_flat theme. Colors used to be like this:
<img width="843" alt="correct" src="https://cloud.githubusercontent.com/assets/230214/13427966/a3e84fe6-dfb7-11e5-82d3-fa364fe9a7f9.png">
Now they look like this:
<img width="841" alt="incorrect" src="https://cloud.githubusercontent.com/assets/230214/13427955/972e3464-dfb7-11e5-87ab-c5455eaf36cd.png">
Is there any configuration option I can set to get the original colors back?

**Comment by chrisbra** [comment]
Am 2016-03-01 14:19, schrieb Andriy Yurchuk:
> I noticed that 6d3710e [1] completely changed the colors I used to
> have in base16_flat theme. Colors used to be like this:
>  [2]
> Now they look like this:
>  [3]
> Is there any configuration option I can set to get the original colors
> back?

I think there was no base16-flat theme before. Try using the default 
base16 theme.

**Comment by Ch00k** [comment]
Indeed executing `:AirlineTheme base16` I get the colors I used to have. What exactly do I need to put in my vimrc to make it persistent?

**Comment by Ch00k** [comment]
`let g:airline_theme='base16'` is the line that should be put in vimrc.
