### ISSUE TITLE
Themes won't work when using Tmux in terminal

### ISSUE THREAD

**Issue by ariajafari** [vim-airline/vim-airline-themes#220]
#### environment

- vim: 8.2.1119
![aa](https://user-images.githubusercontent.com/43445747/87484600-d4027880-c64b-11ea-98e3-c7685949800e.png)

- vim-airline: 0.11
- colorscheme: no colorscheme
- OS: Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
- Have you reproduced with a minimal vimrc: ?yes
- What is your airline configuration:   let g:airline_powerline_fonts = 1
  let g:airline_theme='powerlineish'

if you are using terminal:
- terminal: GNOME Terminal
- $TERM variable: xterm-256color
- color configuration (:set t_Co?): 
if you are using Neovim:
- does it happen in Vim: ???

#### actual behavior

Themes won't work when using Tmux in terminal

#### expected behavior

Themes should work weather Tmux is running or not

**Comment by chrisbra** [comment]
> color configuration (:set t_Co?):

So what about that?

**Comment by ariajafari** [comment]
> > color configuration (:set t_Co?):
> 
> So what about that?

t_Co=256

**Comment by chrisbra** [comment]
does it work with any other theme? What about the graphical version (gvim)? Does (un-)setting termguicolors make any difference?

**Comment by ariajafari** [comment]
I have tried most of the themes and all of them had the problem. Setting or unsetting the termguicolors makes no difference. I don't have gvim installed. 
When I exit Tmux all of themes work correctly.

**Comment by kazukazuinaina** [comment]
Remove `set termguicolors` and add the following configuration to `~/.tmux.conf` I think adding it would fix the problem.

## tmux.conf

```
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
```

I don't think this is a vim-airline issue.

**Comment by ariajafari** [comment]
I made the file .tmux.conf in my home directory and pasted those two lines in the file. But the problem still persists.

**Comment by kazukazuinaina** [comment]
It does not reappear.
Please reload the tmux and try.

**Comment by ariajafari** [comment]
As you mentioned it was tmux's problem. I reinstalled tmux and the problem solved. Thanks a lot.
