### ISSUE TITLE
Question: how to change to dark/light/etc... modes of themes?

### ISSUE THREAD

**Issue by aderchox** [vim-airline/vim-airline-themes#221]
#### environment

- vim: 8.1
- vim-airline: latest
- colorscheme: papercolor
- OS: Ubuntu Focal Fossa
if you are using terminal:
- terminal: Konsole
- $TERM variable: xterm-256color
- color configuration (:set t_Co?): 256

#### actual behavior

Are the themes supported by vim-airline-themes separate from the ones in the main repositories of those themes? For instance, I'm not sure if vim-airline-themes can support the light variant of the papercolor? Currently there's just the dark one? The official repository of the papercolor suggests adding this line:
```set background=light```
but it's not working, I guess it only works when I install their theme directly and not through the vim-airline-themes?
 
#### expected behavior

use the papercolor light mode

**Comment by chrisbra** [comment]
the theme needs to explicitly check the value of the background option. I don't think the theme does it currently. So this would need an adjustment for the existing papercolor theme. PR welcome.

**Comment by aderchox** [comment]
@chrisbra So you mean it's something irrelevant to the vim-airline-themes and requires change in the papercolor theme if I'm not mistaken? (thank you)

**Comment by chrisbra** [comment]
yes, correct. Look at the existing theme: https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/papercolor.vim

It does not distinguish `light/dark` background color.
