### ISSUE TITLE
Papercolor inactive tabs color is missing

### ISSUE THREAD

**Issue by PetarMetodiev** [vim-airline/vim-airline-themes#222]
#### environment

- vim: neovim v0.5.0-nightly-1077-g48c219829
- vim-airline: latest
- colorscheme: papercolor
- OS: MacOS Mojave

#### actual behavior

After an [update](https://github.com/vim-airline/vim-airline/commit/6a1c2a74e91b10c5181fd43ff111831b146c11e1) in vim-airline, papercolor no longer shows different colors for active tab vs inactive tabs

#### expected behavior

Active tab should have different color from inactive tabs. This was the behaviour before the change in vaim-airline

#### screen shot (if possible)

Actual behaviour:
![image](https://user-images.githubusercontent.com/6378306/91033369-edfc8700-e60b-11ea-985c-21b9ad2a763c.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/6378306/91033169-9fe78380-e60b-11ea-84ed-fd35dd01b716.png)

#### additional notes
This is issue does not seem to be present with other themes.

**Comment by chrisbra** [comment]
how about a PR?
