### ISSUE TITLE
Wrong bar colors with nord theme in vim, everything fine in neovim

### ISSUE THREAD

**Issue by danielfalbo** [vim-airline/vim-airline-themes#228]
#### environment

- vim: 8.1.2292
- vim-airline: latest as Sep 4th 2020 (commit 51f599e2cf45c17759b4bd3931ca1c5c10bfd4f4)
- colorscheme: none
- OS: macOS Catalina 10.15.6
- Have you reproduced with a minimal vimrc: yes, with
```
call plug#begin('~/.vim/autoload/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

set termguicolors
let g:airline_theme='base16_nord'
```
- What is your airline configuration: see vimrc above
if you are using terminal:
- terminal: Alacritty 
- $TERM variable: screen-256color
- color configuration (:set t_Co?): 256
if you are using Neovim:
- does it happen in Vim: in Neovim everything works fine

#### actual behavior

wrong colors in vim, everything fine in neovim

#### expected behavior

red airline background in normal mode for the theme 'base16_nord'

#### screen shot (if possible)
![Screenshot 2020-09-05 at 12 48 11](https://user-images.githubusercontent.com/39460524/92303608-c8aa3a00-ef76-11ea-8276-37b06963ed43.png)

**Comment by kazukazuinaina** [comment]
It did not reappear.
Perhaps the problem is that set termguicolors is enabled in neovim, but not in vim. Can you check the configuration again?

**Comment by danielfalbo** [comment]
Weird!
![output](https://user-images.githubusercontent.com/39460524/92304552-5427c900-ef7f-11ea-9cde-dcf900afc9b0.gif)

**Comment by kazukazuinaina** [comment]
What happens when I update my Vim to the latest version?

**Comment by danielfalbo** [comment]
Oh yes! I think my problem is that I'm using macOS's built-in vim.
I'm gonna update vim and try again

**Comment by kazukazuinaina** [comment]
The built-in Vim on macOS is built with the termguicolors option disabled.
Therefore, if you want to enable termguicolors, you need to build it yourself.

**Comment by danielfalbo** [comment]
Thank you much!
