### ISSUE TITLE
Base16 Atelier Forest looks really ugly

### ISSUE THREAD

**Issue by Ketsuban** [vim-airline/vim-airline-themes#23]
I use the `base16-atelierforest` colour scheme; airline picks the `base16_atelierforest` theme which turns the statusbar an ugly green and black, rather than the `base16` theme which looks more correct.
![screenshot from 2016-03-02 10-03-54](https://cloud.githubusercontent.com/assets/5253816/13457087/20984572-e05e-11e5-814a-03a732a8ef5c.png)
I can work around this by setting `g:airline_theme` in my `vimrc`, but I'm not sure what's going on—is `base16_atelierforest` not inheriting data from `base16` when it's supposed to?

**Comment by chrisbra** [comment]
The various base16 themes have been generated externally and do not inspect the base16 theme. If you don't like those specific themes, please set the `g:ailrine_theme` variable, as documented. Closing.
