### ISSUE TITLE
wrong color

### ISSUE THREAD

**Issue by Altair-POD** [vim-airline/vim-airline-themes#233]
#### environment

- vim: VIM - Vi IMproved 8.1 
- vim-airline: v0.11
- colorscheme: N/A
- OS: pop os 20.04
- Have you reproduced with a minimal vimrc: no
- What is your airline configuration: 
 let g:airline_powerline_fonts = 1
 let g:airline_theme='minimalist'

if you are using terminal:
- terminal: gnome-terminal
- $TERM variable: xterm-256color: command not found
- color configuration (:set t_Co?): 256
if you are using Neovim: no
- does it happen in Vim: no

#### actual behavior

white ash color

#### expected behavior

gray color

**Comment by chrisbra** [comment]
Missing information
