### ISSUE TITLE
Add vim-code-dark theme

### ISSUE THREAD

**Issue by ndavidpsi** [vim-airline/vim-airline-themes#237]
Would it be possible to add this theme?
https://github.com/tomasiser/vim-code-dark

**Comment by chrisbra** [comment]
it would. But to make full use of it, you have to clone it to use the colorscheme. And if you are already cloning the repository, then you can simply use that theme that comes with it.

**Comment by ndavidpsi** [comment]
I use that theme. Is it easy to implement it in vim-airline?

**Comment by chrisbra** [comment]
you mean that color scheme? If you already cloned it, than you should be able to simply use the included vim-airline theme

**Comment by ndavidpsi** [comment]
Oh I just have to simply move the file?

**Comment by chrisbra** [comment]
no, besides installing/cloning that repository, you don't have to do anything. vim-airline should pick it up automatically and if you use `:AirlineThemes` you should also be able to automatically complete it to codedark by typing the beginning of the letters and pressing `<Tab>`
