### ISSUE TITLE
Base 16 Tomorrow Night Eighties Theme

### ISSUE THREAD

**Issue by ShiromMakkad** [vim-airline/vim-airline-themes#243]
Can we get the Base 16 Tomorrow Night Eighties theme? I think this repo is missing some base16 themes anyways, and I don't mind generating them with a base16 builder and putting in a PR, but I need the `.mustache` files to do that. Is this possible to add?

**Comment by chrisbra** [comment]
Those base16 themes have been generated, don't know how. If you can create missing themes please create a PR for those.

**Comment by ShiromMakkad** [comment]
I was able to find the `.mustache` files while working on my base16-jetbrains-ide, and I have all the themes built. I can probably get a PR in today.
