### ISSUE TITLE
airline: The specified theme "kolor" cannot be found

### ISSUE THREAD

**Issue by gamersover** [vim-airline/vim-airline-themes#245]
Any airline theme cannot be found. This is my .vimrc config:
![image](https://user-images.githubusercontent.com/26238198/103449676-c23e8b80-4ce6-11eb-9959-cf1310adf3ad.png)

vim-airline and vim-airline-themes is the lastest version
![2021-01-02 10-42-34 的屏幕截图](https://user-images.githubusercontent.com/26238198/103449747-a687b500-4ce7-11eb-9e86-8deb050e094c.png)
![2021-01-02 10-45-53 的屏幕截图](https://user-images.githubusercontent.com/26238198/103449752-b606fe00-4ce7-11eb-9be6-6f1122d2c26c.png)

And all theme exists in `.vim/bundle/vim-airline-themes/autoload/airline/themes`
![2021-01-02 10-48-43 的屏幕截图](https://user-images.githubusercontent.com/26238198/103449811-6aa11f80-4ce8-11eb-97bf-9e2649595961.png)

But set theme just don't work for me, please help
![2021-01-02 10-51-35 的屏幕截图](https://user-images.githubusercontent.com/26238198/103449819-81e00d00-4ce8-11eb-8edb-279681736114.png)

**Comment by chrisbra** [comment]
Is kolor there?

**Comment by gamersover** [comment]
Yeah. Not only kolor, all themes have same error.

**Comment by XiKuuKy** [comment]
I'm also experiencing this.

**Comment by chrisbra** [comment]
can you show the directory structure? What Vim version? What kind of plugin manager?

**Comment by chrisbra** [comment]
can you provide a sample repository that shows this error?

**Comment by chrisbra** [comment]
any updates here?

**Comment by gamersover** [comment]
No, may be I should reinstall them. @XiKuuKy have you solved it?

**Comment by XiKuuKy** [comment]
Mine was a package manager issue. I am using minpac and I needed to call a function.

**Comment by gamersover** [comment]
Put `Plugin 'vim-airline/vim-airline-themes'` in my vimrc file, and finally its work! Sorry to bother you and thank you!
