### ISSUE TITLE
commit fa3911e changes how base16_gruvbox_dark_hard is loaded

### ISSUE THREAD

**Issue by Happy-Dude** [vim-airline/vim-airline-themes#250]
Hey team, just started up neo/vim and realized that the airline theme was loaded differently.
Checked to see what the cause may be and found that commit fa3911ebbdf80a88dcab7c948de33865c8b161ed was merged in.

Unfortunately I'm not too knowledgeable about vim-theming, but I hope the following info + screenshots can help.

#### environment

- vim: vim 8.2.2756 (installed via Homebrew), neovim v0.5.0-dev+nightly-631-gd19348923 (installed via Homebrew, following HEAD)
- vim-airline: commits fa808d74e0aacf131337b58f01ee45fd3d3588af (expected behavior), fa3911ebbdf80a88dcab7c948de33865c8b161ed  (new behavior)
- colorscheme: [base16_gruvbox_dark_hard](https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/base16_gruvbox_dark_hard.vim)
- OS: macOS Catalina 10.15.7
- Have you reproduced with a minimal vimrc: No (please let me know if requested)
- What is your airline configuration: from my [dotfiles repo](https://github.com/Happy-Dude/dotfiles/blob/master/vim/.vim/vimrc/packages/airline.vim)

if you are using terminal:
- terminal: occurs in both Alacritty and iTerm
- $TERM variable: tmux-256color (in Alacritty), xterm-256color (in iTerm)
- color configuration (:set t_Co?): t_Co = 256 (in vim); neovim not set

if you are using Neovim:
- does it happen in Vim: yes, occurs in both vim + neovim

#### actual behavior

![Screen Shot 2021-04-15 at 10 34 20 AM](https://user-images.githubusercontent.com/1098725/114897241-ac0c9500-9dd6-11eb-9d47-2db6e21794cb.png)

#### expected behavior

![Screen Shot 2021-04-15 at 10 30 28 AM](https://user-images.githubusercontent.com/1098725/114897275-b0d14900-9dd6-11eb-8a98-a18552e810d9.png)

#### screen shot (if possible)

Please see above

**Comment by Happy-Dude** [comment]
I don't think the it quite fixed yet; can we reopen and investigate further?

![Screen Shot 2021-04-15 at 12 00 43 PM](https://user-images.githubusercontent.com/1098725/114909017-4cb48200-9de2-11eb-8e49-5727a18039ea.png)

**Comment by chrisbra** [comment]
You might need to dig out further the differences, if it isn't fixed yet.

**Comment by Happy-Dude** [comment]
I gave a shot at fixing it re: https://github.com/vim-airline/vim-airline-themes/pull/251/files

Feel free to make suggestions/edits!
