### ISSUE TITLE
base16 themes are almost all the same

### ISSUE THREAD

**Issue by Felixoid** [vim-airline/vim-airline-themes#252]
#### environment

- vim: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55) Included patches: 1-2489
- vim-airline: 07ab201a272
- colorscheme: base16_ashes
- OS: Arch linux
- Have you reproduced with a minimal vimrc: 

```
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-airline/vim-airline'
call plug#end()

let g:airline_theme = 'base16_ashes'
```

- What is your airline configuration: see above
if you are using terminal:
- terminal: alacritty
- $TERM variable: xterm-256color, screen-256color
- color configuration (:set t_Co?): t_Co=256
if you are using Neovim:
- does it happen in Vim: ???

#### actual behavior

After https://github.com/vim-airline/vim-airline-themes/commit/fa3911ebbdf80a88dcab7c948de33865c8b161ed most of the randomly checked base16* themes looks the same (the left part on the screenshot)

#### expected behavior

The right part of the screenshot, the commit https://github.com/vim-airline/vim-airline-themes/commit/fa808d74e0aacf131337b58f01ee45fd3d3588af

#### screen shot (if possible)

![screen_2021-04-17-00-32-32](https://user-images.githubusercontent.com/3025537/115090721-e6308080-9f15-11eb-8ec3-0fdc1fe57cf8.png)

**Comment by elleven11** [comment]
yeah, my gruvbox theme transformed into a black/white theme:
https://imgur.com/Anktlkc.png

**Comment by Happy-Dude** [comment]
There was a similar issue with https://github.com/vim-airline/vim-airline-themes/issues/250

It's worth pinging @ShiromMakkad to see how the color schemes were changed and how they were validated as correct or still working in https://github.com/vim-airline/vim-airline-themes/pull/244

If the code isn't easy to fix, then perhaps it's worth rolling the commit back and cherry-picking the ones that are still working as intended?

**Comment by chrisbra** [comment]
okay, we just may need to revert that PR #244

**Comment by Felixoid** [comment]
Please, I am begging you to do so ^_^

**Comment by justinpage** [comment]
@Felixoid What happens if you set the following: `let g:airline_theme = 'base16'`? Does that match the colors you expect?

**Comment by ensia96** [comment]
After update, the 'base16_gruvbox_dark_hard' theme is not working properly.

Seeing that the 'red' color looks like the 'original red', it seems that the color values ​​aren't being reflected properly.

Sorry for not providing detailed information. : (

**Comment by felipemlemos** [comment]
The same is happening with base16_monokai.
I did a revert on my machine of #244 and it fixed it for me. It seems it is probably happening with other themes as well.
Do you mind if I create a PR to fix base16_monokai?

**Comment by Felixoid** [comment]
@justinpage hello. I am not sure what do you mean by "colors I expect". I don't use the scheme. But it looks definitely different compared to working commit  
![Screenshot_20210502_123725](https://user-images.githubusercontent.com/3025537/116810352-9c65ae00-ab43-11eb-9a64-bc5932d8359d.png)

Can you, maybe, consider reverting #244 and make a proper update lately? The current state looks very wrong to me

**Comment by btalb** [comment]
Also would support reverting. My themes have gone from left to right since recent updates:

![airline_themes_base16](https://user-images.githubusercontent.com/3508780/117425923-a550e800-af66-11eb-98b6-15f2ed702858.png)

None of the base16 themes seem to change from this new washed out normal mode.

Possibly not the best place to ask, but what I've never understood is why all the different base16 themes are needed. Can't you just set the base16 scheme in your terminal app, and then vim outputs the same ANSI escape codes for every base16 colour scheme? 

So all that would be required here is the different airline modes like [TmuxLine's airline, airline_insert, airline_visual themes(https://github.com/edkolev/tmuxline.vim)?

**Comment by chrisbra** [comment]
Okay, if I haven't done anything wrong, it should be reverted now. I don't know how to revert in git very well, so I hope I did not brake too much :/

**Comment by elleven11** [comment]
There is a bigger problem now. The theme colors are all off.
Didn't remember Gruvbox looked like this https://imgur.com/FiEOnwh.png
😆

**Comment by chrisbra** [comment]
Hm, are those now not like: fa808d74e0aacf131337b58f01ee45fd3d3588af ?
