### ISSUE TITLE
There seems to be a problem with (#252) and (changes in vim-airline repository).

### ISSUE THREAD

**Issue by ensia96** [vim-airline/vim-airline-themes#255]
#### environment

- vim: NVIM v0.4.4
- vim-airline: latest (commit : 19360ba)
- colorscheme: 'base16_gruvbox_dark_hard'
- OS: mac OS Catalina (version 10.15.7)
- Have you reproduced with a minimal vimrc: No.
   - But, I used a setup that previously worked without problems.
- What is your airline configuration: 
```
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

let g:airline_theme = 'base16_gruvbox_dark_hard'

function! AccentDemo()
   let keys = ['춤','추','는','망','고']
   for k in keys
     call airline#parts#define_text(k, k)
   endfor
   call airline#parts#define_accent('춤', 'red')
   call airline#parts#define_accent('추', 'red')
   call airline#parts#define_accent('는', 'red')
   call airline#parts#define_accent('망', 'red')
   call airline#parts#define_accent('고', 'red')
   let g:airline_section_a = airline#section#create(keys)
 endfunction

autocmd VimEnter * call AccentDemo()
 let g:airline#extensions#tabline#fnamemod = ':t'          " vim-airline 버퍼 목록 파일명만 출력
 let g:airline#extensions#tabline#buffer_nr_show = 1       " buffer number를 보여준다
 let g:airline#extensions#tabline#buffer_nr_format = '%s:' " buffer number format
 let g:airline#extensions#tabline#enabled = 1
 let g:airline#extensions#tabline#left_sep = ' '
 let g:airline#extensions#tabline#left_alt_sep = '>>>'
 let g:airline#extensions#branch#enabled = 1
 let g:airline#extensions#default#layout = [
 \ [ 'a', 'b', 'c'],
 \ [ 'z']
 \ ]
```
if you are using terminal:
- terminal: iTerm2
- $TERM variable: xterm-256color
- color configuration (:set t_Co?): Sorry. I don't know how to check this.

if you are using Neovim:
- does it happen in Vim: I only use NVim, so I didn't checked.

#### actual behavior

```
NERDTree: No trees to mirror
/Users/ensia96/.vim/plugged/vim-airline/autoload/airline/extensions/tabline.vim 수행중 에러 발견:
 287 줄:
E488: 끝에 문자가 더 있습니다
 288 줄:
E133: :return이 함수 안에 있지 않습니다
 299 줄:
E488: 끝에 문자가 더 있습니다
 306 줄:
E133: :return이 함수 안에 있지 않습니다
 347 줄:
E133: :return이 함수 안에 있지 않습니다
 352 줄:
E133: :return이 함수 안에 있지 않습니다
 357 줄:
E133: :return이 함수 안에 있지 않습니다
 361 줄:
E133: :return이 함수 안에 있지 않습니다
 363 줄:
E133: :return이 함수 안에 있지 않습니다
 366 줄:
E133: :return이 함수 안에 있지 않습니다
 379 줄:
E488: 끝에 문자가 더 있습니다
 404 줄:
E133: :return이 함수 안에 있지 않습니다
 406 줄:
E133: :return이 함수 안에 있지 않습니다
 408 줄:
E133: :return이 함수 안에 있지 않습니다
 410 줄:
E133: :return이 함수 안에 있지 않습니다
 438 줄:
E133: :return이 함수 안에 있지 않습니다
 440 줄:
E133: :return이 함수 안에 있지 않습니다
 445 줄:

line/vim-airline-themes.
/Users/ensia96/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim 수행중 에러 발견:

  57 줄:
E488: 끝에 문자가 더 있습니다:       # Neovim Terminal
계속하려면 엔터 혹은 명령을 입력하십시오
```

#### expected behavior

I thought the most recent commit would solve the problem of applying an existing theme.

But actually when I start vim like above I get an error and the theme is not applied.

This is just a guess, but both vim-airline and airline_theme seem to have issues right now.

#### screen shot (if possible)

https://user-images.githubusercontent.com/59986267/117529340-0e416a00-b012-11eb-812f-9f6f70c1dd7a.mov

**Comment by chrisbra** [comment]
so what is the problem with the themes?

**Comment by ensia96** [comment]
As you can see in the video, the theme is not applied.

It only applies if I made a direct change using the `:AirlineTheme base16_gruvbox_dark_hard` command.

Should I only create color related issues in this repository? If so, I'm sorry..

If it is an issue that needs to be created in the vim-airline repository, I will recreate it.

![스크린샷 2021-05-08 오후 4 03 42](https://user-images.githubusercontent.com/59986267/117530251-046e3580-b017-11eb-9895-3287f1a58789.png)

**Comment by chrisbra** [comment]
can you please check with an updated vim-airline (at least commit 7e295c859f491f4b282242259286a4603311821c)? I think that should have fixed the neovim errors and I suspect loading themes will work again then. Also when reporting errors, please make sure to run vim/neovim with an english locale, so I am able to read the actual error messages.

**Comment by ensia96** [comment]
Oh, sorry.

I apologize for the lack of consideration as I have very little experience creating issues like this.

I checked after `:PlugUpdate` and it works perfectly!

Thank you for your hard work. : )
