### ISSUE TITLE
base16_dracula has been removed for some reason

### ISSUE THREAD

**Issue by gibboni** [vim-airline/vim-airline-themes#256]
Hi!
I just updated my airline-themes and noticed that the base16_dracula theme was removed. Any particular reason for this? Is it possible to get it back? For now I added it back manually.

**Comment by mikedfunk** [comment]
Also `base16_horizon_terminal_dark`. There were a bunch of themes removed. I locked this repo at a specific commit before they were removed for now. I'm fine with tweaks to themes and adding new ones but being able to set an available theme and not have to worry about it is the whole reason I use this package. Can we please not remove themes?

**Comment by chrisbra** [comment]
should be fixed by 3588b3fd57bbfb4
