### ISSUE TITLE
Colors correct only when t_Co=8

### ISSUE THREAD

**Issue by sphaugh** [vim-airline/vim-airline-themes#26]
I'm using ConEmu + Git Bash + vim. I have 256 colors (ANSI X3.64 / xterm) enabled in the ConEmu settings, and Solarized Dark (Luke Maciak) as the color pallette. 

I need to `set t_Co=256` to prevent vim from overriding the color palette after exiting, but when I do this the colors for airline are completely wrong. 

When I exclude the `set t_Co=256` statement the syntax highlighting is wrong in vim and the terminal color palette is overwritten as well, but airline appears as expected. I run `set t_Co?` and the value returned is 8. Also, `echo $TERM` returns `cygwin` but changing it to something like `xterm` hasn't seemed to help.

**Comment by chrisbra** [comment]
Yes, if your terminal supports 256 colors, you need to set t_Co=256. You might need to configure your $TERM to xterm-256color, then it should work correctly automatically, assuming conEmu supports this.
