### ISSUE TITLE
Bold text in cterm breaks the color in base16-vim

### ISSUE THREAD

**Issue by henry-hsieh** [vim-airline/vim-airline-themes#260]
#### environment

- vim: neovim v0.5.0 / vim v8.1.2269
- vim-airline: commit 0de4c9d
- colorscheme: base16-shell (base16-vim)
- OS: Ubuntu-20.04 (kernal: 5.10.16.3-microsoft-standard-WSL2)
- Have you reproduced with a minimal vimrc:
```vim
silent! call plug#begin('~/.vim/plugged')
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" base16
let base16colorspace=256
source ~/.vimrc_background

" Vim-airline
let g:airline_theme='base16_shell'
```
- What is your airline configuration:
```vim
let g:airline_theme='base16_shell'
```
if you are using terminal:
- terminal: Windows Terminal
- $TERM variable: xterm-256color / tmux-256color
- color configuration (:set t_Co?): Not used
if you are using Neovim:
- does it happen in Vim: yes

#### actual behavior

The vim-airline uses bold texts on A and Z sections by default. Because I didn't turn on the `termguicolors`, the `cterm=bold` actually uses Brighter Black as foreground color in Normal mode even if the color code is Darker Black (`ctermfg=0`). The Brighter Black foreground makes the texts hard to read. My terminal color is set by [base16-shell](https://github.com/chriskempson/base16-shell). The screenshots of airline and its highlight are shown in second figure and third figure. As you can see, airline_a_bold and airline_z_bold are set to bold and the foreground color is set to color 0 (Darker Black).

#### expected behavior

When I change to other mode, the issue is gone. The screenshots of airline and its highlight are shown in fourth figure and fifth figure. The airline_a_bold and airline_z_bold are set to bold and the foreground color is set to color 18 (the second most Darker Black in the scheme). This is because the color is set to base01 in [visual mode's setting](https://github.com/vim-airline/vim-airline-themes/blob/97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256/autoload/airline/themes/base16_vim.vim#L148). In contrast, the color is set to base00 in [normal mode's setting](https://github.com/vim-airline/vim-airline-themes/blob/97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256/autoload/airline/themes/base16_vim.vim#L97). As shown in sixth figure, the color code of base01 is 18, and the color code of base00 is 0. The first eight colors of palette have their bold colors (map to following eight colors). The bold color of base00 is base03, and the bold color of base01 is still base01. If I turn on the `termguicolors`, vim-airline directly uses the RGB color, the foreground color is set to base00.

#### screen shot (if possible)
![1. Terminal color](https://user-images.githubusercontent.com/22725367/131965806-c59c650f-92ca-4e19-b6ed-302b37fa8b03.png)
![2. Normal mode airline color](https://user-images.githubusercontent.com/22725367/131966485-b4a35989-a9b8-4034-940f-38d1afbe18a2.png)
![3. Normal mode airline highlight](https://user-images.githubusercontent.com/22725367/131967658-013e9695-a307-4a62-8b8c-16eb5beb2745.png)
![4. Visual mode airline color](https://user-images.githubusercontent.com/22725367/131968107-fde78fa3-79e3-49a8-97bf-a01c28b53b3a.png)
![5. Visual mode airline highlight](https://user-images.githubusercontent.com/22725367/131968441-a98a969f-d5d1-4351-b5b9-9f8c11b6fb5a.png)
![6. Base 16 Tomorrow Night Scheme of base16-shell](https://user-images.githubusercontent.com/22725367/131969489-37b755fa-4ea8-4762-bc00-9ffbe43840bb.png)

**Comment by chrisbra** [comment]
you can try to remove the bold mode by using the accent=none (see the help)

**Comment by henry-hsieh** [comment]
> 
> 
> you can try to remove the bold mode by using the accent=none (see the help)

Sorry, I don't see accent option in neovim or vim. Or we can remove cterm=bold in this [line](https://github.com/vim-airline/vim-airline/blob/0de4c9df21abf9256091d205148601f718d3a12c/autoload/airline/highlighter.vim#L159) in vim-airline to achieve that.

**Comment by chrisbra** [comment]
Did you check the help for vim-airline? `:h airline-accents` (https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L1815)

**Comment by henry-hsieh** [comment]
> 
> 
> Did you check the help for vim-airline? `:h airline-accents` (https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L1815)

Sorry, I didn't check that. After I add following setting in .vimrc, the problem is fixed. Thanks for your help!

```vim
call airline#parts#define_accent('mode', 'none')
call airline#parts#define_accent('linenr', 'none')
call airline#parts#define_accent('maxlinenr', 'none')
call airline#parts#define_accent('colnr', 'none')
```
