### ISSUE TITLE
Overlapping UI elements

### ISSUE THREAD

**Issue by SinTan1729** [vim-airline/vim-airline-themes#264]
#### environment

- vim: vim 8.2.3890-1
- vim-airline: latest from git (Jan 2 2022)
- colorscheme: Dark
- OS: Linux (ENdeavourOS)
- Have you reproduced with a minimal vimrc: Yes
- What is your airline configuration: Vanilla with themes installed
if you are using terminal:
- terminal: Alacritty
- $TERM variable: screen256color
- color configuration (:set t_Co?): 256
if you are using Neovim: No
- does it happen in Vim: Yes

#### actual behavior

Overlapping areas.

#### expected behavior

Should be perfect.

#### screen shot (if possible)

This is using the minimalist theme (look at extreme right). Similar things happen with all other themes.
![image](https://user-images.githubusercontent.com/35728385/147871340-ff1f6a8f-484c-488a-8a44-a3a0112c74d8.png)

**Comment by chrisbra** [comment]
this is most likely an issue with your font. Please try a different one.

**Comment by SinTan1729** [comment]
I've tried using Noto Mono and Source Code Pro (this screenshot is using SCP). Both have the same issue. Can you suggest a font to try (i.e. that you know works)?

**Comment by chrisbra** [comment]
No, I cannot. Alternatively, try to use a different `colnr` symbol:

    let g:airline_symbols.colnr = ' '

Or just use any other symbol you like.

**Comment by SinTan1729** [comment]
> `let g:airline_symbols.colnr = ' '`

This seems to have done the trick.
