### ISSUE TITLE
(Solved by me) Is the list of themes an skeleton?

### ISSUE THREAD

**Issue by jazei-AR** [vim-airline/vim-airline-themes#276]
#### environment

- vim: 9
- vim-airline: 0.11
- colorscheme: defaullt
- OS: linux mint 21
- Have you reproduced with a minimal vimrc: ???
- What is your airline configuration: standard
if you are using terminal:
- terminal: bash
- $TERM variable: ???
- color configuration (:set t_Co?): 
if you are using Neovim:
- does it happen in Vim: ???

#### actual behavior

when I try to change the theme from the list I get this message "cannot be found" see screenshot.
steps:
:AirlineTheme <Ctrl>d
appear the list
:Airline theme: atomic for example
Message: Airline can not found that theme
I found the clue: the semicolon : between Airline theme and the name written by me, If I delete : Fixed! I'm enjoing the Themes!!!!!
Just delette : 
see screenshot for see the :
### expected behavior

change the theme, like when I do Airlinetheme Random
![Captura de pantalla de 2023-02-04 16-56-39](https://user-images.githubusercontent.com/72522918/216788303-deded1ed-29c7-4234-b05a-3fd276f37632.png)

**Comment by chrisbra** [comment]
closing then.
