### ISSUE TITLE
Issue when loading the theme

### ISSUE THREAD

**Issue by montalvomiguelo** [vim-airline/vim-airline-themes#3]
I have Janus Vim distribution and I have tried to do the following in my `.vimrc.before`
```
" Airline Theme
let g:airline_theme = 'powerlineish'
```
If I do `$ vim .` powerlineish is well displayed at left side but right side has not loaded the theme properly, even if I have not chosen any Theme in my `.vimrc.before` and __dark__ is default theme...
<img width="794" alt="screen shot 2016-02-01 at 6 51 45 pm" src="https://cloud.githubusercontent.com/assets/5134470/12736333/e0d78e9e-c914-11e5-838e-68939a881c4e.png">
If I resize the terminal or do `<C-w>l` to go Right or open a file, then the Theme is loaded at Right side. The issue does not happen when I try to edit a file directly ex. `$ vim hello.txt`
<img width="794" alt="screen shot 2016-02-01 at 7 04 07 pm" src="https://cloud.githubusercontent.com/assets/5134470/12736527/9aa1e7d8-c916-11e5-8b68-2a9dff503cb5.png">
The only way to get themes working well when editing a directory `$ vim .` is by adding this into my `vimrc.after`
```
" Airline Theme
au VimEnter * AirlineTheme powerlineish
```
<img width="794" alt="screen shot 2016-02-01 at 7 16 13 pm" src="https://cloud.githubusercontent.com/assets/5134470/12736709/4de2ab06-c918-11e5-9d24-d9d071fe46df.png">

**Comment by chrisbra** [comment]
Hm, I can't reproduce this. If I run `vim .` Vim opens up with only the FileExplorer opened, e.g. there is no split window open. If I run vim -o file* all windows open correctly as expected.

**Comment by montalvomiguelo** [comment]
I have tried the same as you without nerd tree and only file explorer that does not creat the split and the issue is not appearing ... 

I think is only when you have nerd tree and the split right side has not loaded airline yet

**Comment by chrisbra** [comment]
How do you reproduce this issue?

**Comment by montalvomiguelo** [comment]
I have installed nerd tree and airline even without the airline-themes only with dark default theme... I'm using iterm2...

Then I open current directory in vim $ vim .

**Comment by chrisbra** [comment]
Even with nerdtree installed, `vim .` opens only one single window

**Comment by DanielGGordon** [comment]
The instructions on how to install a theme is quite lacking. Trying to figure out how to install it with pathogen with no luck. Where the hell do I specify the theme? Where do I put the themes??

**Comment by mhartington** [comment]
@DanielGGordon The themes are treated like any other vim plugin. Once you clone the repo, the process doesn't change from there.

```
git clone https://github.com/vim-airline/vim-airline-themes.git ~/.vim/bundle/
```

```viml
let g:airline_theme='dark'
```

**Comment by chrisbra** [comment]
We accept pull requests for better documentation 24/7 ;)

**Comment by montalvomiguelo** [comment]
I'm trying to find What Janus does that creates automatically a split when you open a directory `$ vim .` and only one of the splits loads airline (left side NerdTree), the second split does not untill you go right `<C-w>l`, resize or open a file

**Comment by chrisbra** [comment]
My guess is, it triggers an autocommand, and since by default autocommands do not nest, airline is not called. would need a `<nested>` flag at the autocommand definition.

**Comment by montalvomiguelo** [comment]
Yep so in that case the only way to get loaded airline in both sides is by adding 

```
au VimEnter * AirlineTheme powerlineish
```

**Comment by DanielGGordon** [comment]
@chrisbra I'd be happy to add to the doc at some point. 

So I put

`let g:airline_theme='murrmur'`

In my `.vimrc`. Is that the right place to do it? It works fine for me. I know this isn't the best place to ask, but I don't like opening an issue out of stupidity or ignorance.

**Comment by chrisbra** [comment]
@DanielGGordon Yes that is the correct way.
