### ISSUE TITLE
Issue when using with neovim

### ISSUE THREAD

**Issue by luuhai** [vim-airline/vim-airline-themes#4]
My neovim used to display airline well, but after I updated vim-airline and install vim-airline-themes, the arrows are not rendered right:
![neovim](http://i.imgur.com/NRzF1Jn.png)
Everything seems ok if I use vim:
![vim](http://i.imgur.com/MN8PJtz.png)
Here're some of my airline-related config (I'm using same config for both vim and neovim)
```
autocmd vimenter * AirlineTheme bubblegum
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
```

**Comment by chrisbra** [comment]
is this perhaps: https://github.com/neovim/neovim/wiki/Following-HEAD#20160204

**Comment by luuhai** [comment]
Yes thank you so much :) I remove NVIM_TUI_ENABLE_TRUE_COLOR setting and the line looks good again. But because of this the colorscheme looks a bit off. Now I have to wait for colorschemes' authors to fix their schemes or fix them myself right?

**Comment by chrisbra** [comment]
Please try updating airline. I just merge a pull request, that I think should also fix your issue.

**Comment by luuhai** [comment]
@chrisbra Awesome. Now everything's working right. Thank you so much for your help :+1:
