### ISSUE TITLE
AirlineTheme command not working

### ISSUE THREAD

**Issue by stevesbrain** [vim-airline/vim-airline-themes#40]
Hi there - when using the old repo (vim-airline), I have access to the AirlineTheme command, and can set any themes (except now, there are non in the repo - just "dark"). However, when I replace that with vim-airline-themes (to get access to the themes), the AirlineTheme command does not exist, and so I cannot set any time. Likewise, if I revert back, the command once again appears (so it's not my process, as far as I can tell). Are both repo's supposed to be used in conjunction somehow? 

My Vim game is not superb, so I haven't been able to figure this one out. Using Pathogen by the way. Any help would be appreciated :)

**Comment by chrisbra** [comment]
`:AirlineTheme` command is defined [here](https://github.com/vim-airline/vim-airline/blob/master/plugin/airline.vim#L131) and should still be working. Perhaps your installation is not correct?

**Comment by stevesbrain** [comment]
I think your link has answered this question I posed:

>  Are both repo's supposed to be used in conjunction somehow?

Evidently, the vim-airline repo must contain just the command then, and the vim-airline-themes contains the themes. Is vim-airline-themes supposed to be a git submodule of vim-themes, or do I simply add this as another folder in bundle folder?

I'd removed vim-airline folder because the error message said the themes had been replaced with vim-airline-themes; I had assumed the entire repo had been migrated. Thanks for clarifying

**Comment by chrisbra** [comment]
Am 2016-05-19 13:34, schrieb Steve Divskinsy:
> I think your link has answered this question I posed:
> 
>> Are both repo's supposed to be used in conjunction somehow?
> 
> Evidently, the vim-airline repo must contain just the command then,
> and the vim-airline-themes contains the themes. Is vim-airline-themes
> supposed to be a git submodule of vim-themes, or do I simply add this
> as another folder in bundle folder?


simply clone the vim-airline-themes repository as another folder is the 
way to go here.

**Comment by stevesbrain** [comment]
Awesome, thanks for clearing that up!
