### ISSUE TITLE
Luna theme has two extra characters

### ISSUE THREAD

**Issue by faurehu** [vim-airline/vim-airline-themes#45]
To the right of my statusline there's two red `<` one of them with a red background.  Everything else is just fine but my OCD is kicking in. Any clues on how to remove them would be very much appreciated.

![image](https://cloud.githubusercontent.com/assets/4634877/16878410/5806287a-4aa4-11e6-84ee-134624fde1a2.png)

**Comment by chrisbra** [comment]
that's to be expected. See the help for the skip_empty setting.

**Comment by faurehu** [comment]
Thank you.
