### ISSUE TITLE
Dracula theme color conflict

### ISSUE THREAD

**Issue by nudzg** [vim-airline/vim-airline-themes#46]
vim-airline-themes included dracula theme has conflicting colors with https://github.com/dracula/vim, which already provides a theme for vim-airline.

Depending on loading order of vim-airline-themes and dracula/vim theme one gets one set of colors or another.

First is the vim-airline-themes version and the second the dracula/vim one:

![airline-dracula](https://cloud.githubusercontent.com/assets/5119900/16952107/24ff8c06-4dc8-11e6-87c4-5c926d0ae06b.png)

**Comment by chrisbra** [comment]
@OndrejSlamecka are you okay, if we remove the dracula theme and depend on dracula/vim for the actual theme?

**Comment by OndrejSlamecka** [comment]
@chrisbra Yes, go for it, dracula/vim's airline theme seems similar to what I did (and moreover sets proper colors for the 256 color theme which I didn't bother to do). 

Just FYI the reason I created my own theme was that at the time the dracula/vim theme used wrong colors for the 24-bit theme (and they didn't care about updating it even though people posted fixes to now deleted GH issue thread).
