### ISSUE TITLE
Theme creation documentation

### ISSUE THREAD

**Issue by brailsmt** [vim-airline/vim-airline-themes#47]
I'm the author of the midnight.vim (and midnight2.vim, they're the same now) colorscheme.  I recently began using neovim and took the opportunity to find new plugins.  Vim-airline is one but none of the colorschemes match well, and I'd like to create my own to match my colorscheme.  The documentation for everything that is in play when creating a vim-airline theme is severely lacking.  Additionally, the mechanism for specifying colors is completely different than colorscheme maintainers are used to.

Theming the statusline is not something that is well documented, such as the colors that are applied when a buffer is modified, and inactive.  I resorted to :echo-ing the color palette, and hand formatting the several hundred lines of the palette before it began to make sense.  Even then, things like 'airline_c50_to_airline_x' and 'airline_c32_to_airline_x' are cryptic, to say the least.  It will take me some time yet, to figure out all the options I have available to me and what each of these things does and when.  I will be doing it by trial and error, but it would be nice if the theming mechanism, events, states, and other things were clearly documented.

**Comment by chrisbra** [comment]
I agree, documentation could be better. I'd appreciate a PR, once you figure it all out ;)

**Comment by brailsmt** [comment]
How can I print the statusline that is generated?  Is there anything besides manually editing airline#statusline()?  That would help with the syntax highlighting, since the groups have to be defined with the '%#HighlightGroup#' syntax.  I'd love to get rid of the different way of specifying the highlighting and just do it the same way vim does, ie. a list of \:hi statements.

**Comment by chrisbra** [comment]
you can do something like `:echo eval(&stl[2:])` That won't display the colors however. That is simply not possible.

**Comment by brailsmt** [comment]
I ended up doing this.  Noisy, but it gets the job done.
```
diff --git a/autoload/airline/builder.vim b/autoload/airline/builder.vim
index 08c383c..a53ceb7 100644
--- a/autoload/airline/builder.vim
+++ b/autoload/airline/builder.vim
@@ -89,6 +89,7 @@ function! s:prototype.build()
   if !self._context.active
     let line = substitute(line, '%#.\{-}\ze#', '\0_inactive', 'g')
   endif
+  echom line
   return line
 endfunction
```

**Comment by brailsmt** [comment]
So, I started over, and I think that you could vastly simplify the color highlighting by defining groups that were more well defined.  The first question I asked myself is why the highlighting for a theme is so different than for regular colorschemes, and it is because the highlighting groups are automatically generated.  I [added some "logging"](https://gist.github.com/brailsmt/e323e4662750d5ab574f136f9fd79c6b) for all the generated highlight groups and ran through a small workflow in vim.  I then :put the contents of the generated highlight groups and a few things come stand out.

1) Some groups are redefined.  For example, in the [gist](https://gist.github.com/brailsmt/e323e4662750d5ab574f136f9fd79c6b), airline_a is redefined 3 times.  This suggests to me that there should be 3 separate highlighting groups.
2) There seems to be a lot of very minor changes between hundreds of highlighting groups.  Which suggests to me that is probably a way to regroup the syntax items in a way that reduces a lot of the duplications.  It may lose some of the extreme flexibility, but would gain a lot of simplicity.  In the end, I don't that that flexibility is needed most of the time, it just happens to be used a lot because it is there.  I think a good approach may be to define/list all the possible highlight groups, then link them to a much smaller subset of highlight groups, much like a lot of syntax definitions.  This would allow anyone to change things however they wanted while keeping most things simple.
3)  There seem to be a few key transitions:
 - active to inactive
 - section I to section J
 - bold to not bold
4) There seems to be a bunch of strange "inactive_inactive" groups, which hurts my brain.

I may look some more into this later, but I think it'd be possible to simplify/overhaul the highlighting scheme to make it more approachable for colorscheme designers.

**Comment by chrisbra** [comment]
Thanks for all that. I'd like to hear @bling  for input.

**Comment by bling** [comment]
@brailsmt the reason highlight groups are generated is because there are so many combinations (as is evident in your gist).  the format was also chosen to simultaneously support terminal and gui colors in a single line for a single mode.

i think everything will make a lot more sense when you read the documentation; it's inline with the default theme: https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/themes/dark.vim

**Comment by brailsmt** [comment]
I did read the documentation in dark.vim, it was what I used to get started on a theme that would fit my colorscheme.  It wasn't very clear, at least to me.

For example, the documentation describes modes.  Ok, I see how the mode is used in the lets, it is part of the dictionary key used in 'g:airline#themes#<colorscheme>#pallette'.  Then the dark.vim file goes on to create 's:N1', 's:N2', and 's:N3'.  Ok, that is pretty terse, but I suppose the 'N' stands for 'normal', 'Normal' might've been a much better choice.  But, WTF does '1', '2', or '3' mean?  Oh, I see each of those are parameter 1, 2, and 3 to generate_color_map...  WTF are the 1st, 2nd, and 3rd parameters?  When are the colors for the 1st parameter used?  2nd?  3rd?  I'm going to assume it is some sort of state change, but what state change?  But wait, maybe it isn't a state change, because there are other things like ''g:airline#themes#<colorscheme>#pallette.normal_modified', that's a state change.  So are there different kinds of state changes, some that have a name like 'modified', 'paste', and then there are these mysterious ones called '1', '2', and '3'.

So, I throw up my hands, change everything to be the same colors and ignore the whole '1', '2', '3' thing, hoping to get some clarification on all the state transitions that trigger different palettes to be applied.  The problem is that as a colorscheme designer, I want my colors to mean certain things and I have absolutely no clue how the internal workings of airline work to determine what those colors are and when they are applied.  I do not know how to map the colors I want for certain modes, states, etc... to an airline colorscheme.  I like the functionality of airline, but the colorscheme definition doesn't make it easy to design a colorscheme without trial and error.

**Comment by bling** [comment]
1, 2, and 3 refer to the 1st, 2nd, and 3rd sections.

    section1 > section2 > section 3                section 4 < section 5 < section6

that is the default configuration.  `generate_color_map` is a convenience function to mirror colors for sections 4, 5, 6.  if you want to define different colors for 4/5/6, you can do so, as others have in the past.

the variable `N1` defines "normal mode, section1".  `I2` would be "insert, section 2", etc.

but to answer your question directly, no, we can't change the format because all the 70+ themes would need to be rewritten, which is impractical.

**Comment by brailsmt** [comment]
That finally makes some sense.

I suggest that instead of calling them 'N1', 'I3', etc... they be called 'normal_a', 'insert_c' to go along with the 'airline_a', 'airline_b', 'airline_c' convention.  I may submit a pull request to do just that.  In general, I think the documentation could be made much less cryptic if these sections were given meaningful names, and not 'airline_a', and 'N1'.  For example i think this is much easier to follow:
```
let g:airline#themes#dark#palette = {}
let s:airline_a_normal   = [ '#00005f' , '#dfff00' , 17  , 190 ]
let s:airline_b_normal   = [ '#ffffff' , '#444444' , 255 , 238 ]
let s:airline_c_normal   = [ '#9cffd3' , '#202020' , 85  , 234 ]
" Mirror airline_a/b/c to airline_x/y/z
let g:airline#themes#dark#palette.normal = airline#themes#generate_color_map(s:airline_a_normal, s:airline_b_normal, s:airline_c_normal)
```

There would be no need to change any existing themes.

**Comment by brailsmt** [comment]
Pull Request for dark.vim:  https://github.com/vim-airline/vim-airline/pull/1225

**Comment by bling** [comment]
let's continue the discussion in the other PR.  thanks.
