### ISSUE TITLE
Powerline font shows wrong on startup

### ISSUE THREAD

**Issue by julytang** [vim-airline/vim-airline-themes#49]
<img width="810" alt="screen shot 2016-08-12 at 1 55 14 pm" src="https://cloud.githubusercontent.com/assets/6831587/17613902/7626cc46-6094-11e6-95bd-c27d6f34d7bc.png">
<img width="318" alt="screen shot 2016-08-12 at 1 55 29 pm" src="https://cloud.githubusercontent.com/assets/6831587/17613903/7b1315f2-6094-11e6-8064-e595674e9408.png">
<img width="153" alt="screen shot 2016-08-12 at 1 56 12 pm" src="https://cloud.githubusercontent.com/assets/6831587/17613909/93802364-6094-11e6-822f-ad7ffb39a0b9.png">
The filename at the statusline has no background color. And there is an strange arrow on the right.But when I edit a file,the color changes,and the arrow becomes normal.
<img width="432" alt="screen shot 2016-08-12 at 1 59 48 pm" src="https://cloud.githubusercontent.com/assets/6831587/17614004/2aada07c-6095-11e6-8c8f-94fdfa7cc75c.png">
<img width="461" alt="screen shot 2016-08-12 at 2 00 03 pm" src="https://cloud.githubusercontent.com/assets/6831587/17614007/2f67acac-6095-11e6-823c-dacc0e4462f0.png">
This problem happens everytime I start my vim.

> :echo airline#statusline(1)
> <img width="915" alt="screen shot 2016-08-12 at 2 04 51 pm" src="https://cloud.githubusercontent.com/assets/6831587/17614073/cbc42274-6095-11e6-9a98-baea63be4a87.png">

**Comment by chrisbra** [comment]
i believe the output of airline#statusline(1) is after you edit something and therefore looks okay.
However, what is the highlight airline_c (`:hi airline_c`)? What is the highlight of Normal group (`:hi Normal`) What is your terminal/gui?

**Comment by chrisbra** [comment]
any update here?
