### ISSUE TITLE
Base16 solarized theme doesn't respect the light

### ISSUE THREAD

**Issue by habitullence** [vim-airline/vim-airline-themes#5]
My config is set to light but when I use this theme I get dark, i.e., base16_solarized doesn't respect background=light.

**Comment by chrisbra** [comment]
does it actually change the background setting? I think those base16_ themes are relatively simple, they don't seem to take 'bg' setting into effect. This would need to be added. Unfortunately I am not good in designing color schemes. So it's best to use a different scheme.

**Comment by megapctr** [comment]
I had a slightly different problem with `base16_solarized` colors, and in my case the solution was to use `base16` theme instead.

**Comment by chrisbra** [comment]
i am closing this. The solution is to use the base16 theme. However I am open for PR which fix this bug for the various base16_xxx themes.

**Comment by habitullence** [comment]
Just came back to this after changing theme and realising I still have an issue. 

Thanks @megapctr, changing to base16 fixed it for me. Looking at vimscript looks like it does some generic wiring. If I have any problems, I'll fix and submit PR for theme.
