### ISSUE TITLE
base16 airline theme

### ISSUE THREAD

**Issue by vaxXxa** [vim-airline/vim-airline-themes#54]
My VIM config:
```VimL
set background=dark
let base16colorspace=256
colorscheme base16-eighties

let g:airline_theme='base16'
```

For shell I use `base16-eighties`.

And see some color problems:

![screenshot 2016-09-20 15 07 44 copy](https://cloud.githubusercontent.com/assets/139175/18669628/909b3a34-7f44-11e6-945d-ec00cfd870ef.png)

**Comment by yevhen-m** [comment]
I have the same issue.

**Comment by chrisbra** [comment]
Am 2016-09-20 14:14, schrieb Vasyl Nakvasiuk:
> My VIM config:
> ```set background=dark
> let base16colorspace=256
> colorscheme base16-eighties
> 
> let g:airline_theme='base16'
> 
> For shell I use base16-eighties.
> 
> And see some color problems:
> 
> ![screenshot 2016-09-20 15 07 44
> copy](https://cloud.githubusercontent.com/assets/139175/18669628/909b3a34-7f44-11e6-945d-ec00cfd870ef.png)

You issue is, that you have an inactive statusline?

**Comment by yevhen-m** [comment]
@chrisbra no, statusline is active in the right window, but text in the left window is invisible (as it is invisible in the tabline).

**Comment by chrisbra** [comment]
Am 2016-09-20 16:01, schrieb yevhen-m:
> @chrisbra [1] no, statusline is active in the right window, but text
> in the left window is invisible (as it is invisible in the tabline).
> 

Yes, I believe that is what the inactive statusline is.
And tabline is visible in both windows. It's the first line with the 
"bootstrap.sh"
that is visible in both windows.

**Comment by vaxXxa** [comment]
> You issue is, that you have an inactive statusline?
@chrisbra The problem in colorscheme (black text on the dark background). For instance, if I use `base16-eighties` vim airline theme, I see next:
![screenshot 2016-09-27 23 30 24](https://cloud.githubusercontent.com/assets/139175/18890596/722f3674-850a-11e6-96b4-f3d54a399403.png)

**Comment by vaxXxa** [comment]
@chrisbra why u have closed this issue?

**Comment by chrisbra** [comment]
see https://github.com/vim-airline/vim-airline-themes/issues/54#issuecomment-248318232

**Comment by chrisbra** [comment]
if you want to suggest changing the colorscheme, go ahead and create a PR

**Comment by vaxXxa** [comment]
Hi @chrisbra 
I've tried to understand, how to change color in `base16` theme, but it's hard to me.
Could you please make text on inactive tab and status line in `base16` 
![909b3a34-7f44-11e6-945d-ec00cfd870ef](https://cloud.githubusercontent.com/assets/139175/19348695/e1364c98-9157-11e6-9db5-f8e248f4a619.png)

like in `base16-eighties`
![722f3674-850a-11e6-96b4-f3d54a399403](https://cloud.githubusercontent.com/assets/139175/19348739/0ecf7896-9158-11e6-95e9-871071eca950.png)
?

**Comment by chrisbra** [comment]
I just pushed a fix.

**Comment by vaxXxa** [comment]
@chrisbra thnx!

**Comment by chrisbra** [comment]
Am 2016-10-18 14:54, schrieb Vasyl Nakvasiuk:
> @chrisbra [1] thnx!

Make sure to read the documentation.
