### ISSUE TITLE
Modified color not updating till I resource my vimrc

### ISSUE THREAD

**Issue by iovis** [vim-airline/vim-airline-themes#58]
Every time I open a new instance of vim, Airline is not correctly updating the "modified" color in the bottom status bar. It solves when I resource my vimrc. How do I debug this?

<img width="1040" alt="screen shot 2016-10-15 at 22 14 16" src="https://cloud.githubusercontent.com/assets/6660202/19413104/e021098c-9324-11e6-88c8-2146d8d1404b.png">
<img width="1040" alt="screen shot 2016-10-15 at 22 14 25" src="https://cloud.githubusercontent.com/assets/6660202/19413103/e01c4744-9324-11e6-800a-27e1374caeaa.png">

**Comment by chrisbra** [comment]
did you modify your vimrc in between?

**Comment by iovis9** [comment]
Nope, same vimrc when I resource it.
