### ISSUE TITLE
jellybeans now showing red bar for tab and status line

### ISSUE THREAD

**Issue by dwieeb** [vim-airline/vim-airline-themes#6]
I recently updated to the latest airline (I had a fairly old version). I am now seeing red as the background for the tab bar and statusline. My jelly beans have been taken away from me. :lollipop: :neckbeard: 

![jellybeans](http://i.imgur.com/Dtg5XtB.png)
![not jellybeans](http://i.imgur.com/MWM1oN8.png)

**Comment by mhartington** [comment]
Make sure you have the the accompanying themes, which have been removed recently 

https://github.com/vim-airline/vim-airline-themes

**Comment by chrisbra** [comment]
I don't know the themes very well. But from a quick glance, it seems like your terminal is not in 256color mode?

**Comment by dwieeb** [comment]
@mhartington Yeah, that's why I'm posting the issue in this repo. :stuck_out_tongue: I have them.

@chrisbra It is in 256color mode. So is vim and all that. Jellybeans looks beautiful in 256, but I've noticed the red bars respond to my ANSI Red color setting.

This led to further investigation. In `jellybeans.vim`, `airline#themes#get_highlight('NonText')` is returning `['', '', '240', 1, '']` (notice the `1`, which is red). I think this is a bug with `NonText`. I would expect the ctermbg to be more like color 233 or something. `zenburn` theme has the same issue.

**Comment by mhartington** [comment]
@dwieeb ok, seeing this as well. 

@chrisbra putting a PR together. It's basically a re-write of the current theme, but in a much more maintainable setup.
