### ISSUE TITLE
monochrome: trailing space block non monochrome

### ISSUE THREAD

**Issue by ariejan** [vim-airline/vim-airline-themes#60]
In the monochrome theme, everything is in nice shades of grey. Everything except the 'trailing space' part. 

<img width="460" alt="1__tmux__tmux_" src="https://cloud.githubusercontent.com/assets/1913/20260939/0ac63a2e-aa5c-11e6-861b-9d0dcb876384.png">

I have no idea how to change this, so if anyone can help you, I'd very much appreciate it.

**Comment by chrisbra** [comment]
If I see that correctly, the monochrome theme does not define the airline_warning and airline_error highlighting groups. Therefore it uses the builtin default. You would have to modify the theme to included an adjusted group name there.

Check other themes on how to do it, preferably the builtin default dark.vim from the vim-airline repository.

If you find a fix, I appreciate a PR.

**Comment by chrisbra** [comment]
See also base16 theme as an example on how to set those groups
