### ISSUE TITLE
base16 templates

### ISSUE THREAD

**Issue by dawikur** [vim-airline/vim-airline-themes#64]
I am currently working on base16-gruvbox schemes.
What I see here; quite a lot of similar code; looks like great candidate for base16 template.

Generating gui and cterm colors is straightforward (https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache).

Issue is with differences between schemes - each one can define its own versions of colors for modes. So for me it would be best to have base16-gruvbox-airline-template instead of base16-aitline-template (like one degree of freedom more).

Have you thought about it?

**Comment by chrisbra** [comment]
I don't understand what you would like to have changed?

**Comment by dawikur** [comment]
Not change, but I am wondering if adding template for base16 colors for airline would be useful and even possible.

**Comment by mshkrebtan** [comment]
@dawikur Are you talking about `vim-airline` color schemes? Take a look at #63. Isn't that what you want? It works good for me for all the Base16 Shell themes I tried.

**Comment by chrisbra** [comment]
So you want to include a template theme. I am still not sure, how this is supposed to work. Do you want the template being sourced by other themes? I think that should work if you use source command, but not sure. I am definitly in favor of such a change.

**Comment by iamsubhranil** [comment]
@chrisbra the template should provide a basic building block for writing a new theme. Newbies(like me) will just have to put appropriate colors in appropriate values.

**Comment by chrisbra** [comment]
that is probably, because most of the base16 themes were somehow auto-generated. BTW: the default dark theme can be used as a template, no?
