### ISSUE TITLE
nothing happens after :AirlineTheme {theme_name}

### ISSUE THREAD

**Issue by kaldown** [vim-airline/vim-airline-themes#65]
Using `Pathogen` 
I have a 
```
ls ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/ | grep luna
luna.vim
```
But after `:AirlineTheme luna` nothing happens.

or even:
`set laststatus=2`
`let g:airline_theme='luna'`

vim 7.4

**Comment by chrisbra** [comment]
you would need to debug, to find out, why nothing happens.

**Comment by viralshah** [comment]
+1. I am facing the same issue pathogen + vim 8. @chrisbra can you provide some steps to debug and I can supply the output back here.

**Comment by chrisbra** [comment]
start with `:debug :AirlineTheme lua` and step through. Read `:h debug-scripts` for what commands you can use (step, continue, next, etc...)

**Comment by viralshah** [comment]
Thanks for such a quick response. I tried this:

:debug :AirlineTheme simple
Entering Debug mode.  Type "cont" to continue.
cmd: AirlineTheme simple
>s
cmd: call <80><fd>Q77_airline_theme("simple")
>s
function <SNR>77_airline_theme
line 1: if a:0
>s
function <SNR>77_airline_theme
line 2: call airline#switch_theme(a:1)
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 1: try
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 2: let palette = g:airline#themes#{a:name}#palette "also lazy loads the theme
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 3: let g:airline_theme = a:name
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 4: catch
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 11: endtry
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 13: let w:airline_lastmode = ''
>s
function <SNR>77_airline_theme[2]..airline#switch_theme
line 14: call airline#load_theme()
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 1: if exists('*airline#themes#{g:airline_theme}#refresh')
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 3: endif
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 5: let palette = g:airline#themes#{g:airline_theme}#palette
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 6: call airline#themes#patch(palette)
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 1: for mode in keys(a:palette)
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 5: if !has_key(a:palette[mode], 'airline_error')
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 7: endif
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 8: endfor

.... MISSING SOME OUTPUT (forgot to copy).....

function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 5: if !has_key(a:palette[mode], 'airline_error')
>echo a:pallette
Error detected while processing function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch:
line    5:
E121: Undefined variable: a:pallette
E15: Invalid expression: a:pallette
>echo a:palette
{'normal_modified': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_warning': ['#000000', '#df5f00', 232, 166], 'airline_c': ['#df0000', '#080808', 160, 232, '']}, 'inactive': {'airline_error': ['#000000', '#990000', 232, 160,
 ''], 'airline_a_to_airline_b_inactive': ['', '', '232', '234', ''], 'airline_x': ['#4e4e4e', '#1c1c1c', 239, 234, ''], 'airline_y': ['#4e4e4e', '#1c1c1c', 239, 234, ''], 'airline_z': ['#4e4e4e', '#080808', 239, 232, ''], 'airline_c_to_air
line_x_inactive': ['', '', '234', '234', ''], 'airline_z_to_airline_warning_inactive': ['', '', '166', '232', ''], 'airline_x_to_airline_y_inactive': ['', '', '234', '234', ''], 'airline_b_to_airline_c_inactive': ['', '', '234', '234', '']
, 'airline_c12_to_airline_x_inactive': ['', '', '234', 'NONE', ''], 'airline_y_to_airline_z_inactive': ['', '', '232', '234', ''], 'airline_warning': ['#000000', '#df5f00', 232, 166, ''], 'airline_c13_to_airline_x_inactive': ['', '', '234'
, '236', ''], 'airline_c7_to_airline_x_inactive': ['', '', '234', '234', ''], 'airline_a': ['#4e4e4e', '#080808', 239, 232, ''], 'airline_b': ['#4e4e4e', '#1c1c1c', 239, 234, ''], 'airline_c': ['#4e4e4e', '#1c1c1c', 239, 234, ''], 'airline
_c10_to_airline_x_inactive': ['', '', '234', 'NONE', '']}, 'replace': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_a': ['#080808', '#af0000', 232, 124, ''], 'airline_warning': ['#000000', '#df5f00', 232, 166]}, 'normal': {'
airline_c10_to_airline_x': ['', '', '232', 'NONE', ''], 'airline_x_to_airline_y': ['', '', '234', '232', ''], 'airline_error': ['#000000', '#990000', 232, 160, ''], 'airline_x': ['#767676', '#080808', 243, 232, ''], 'airline_y': ['#ff5f00'
, '#1c1c1c', 202, 234, ''], 'airline_z': ['#080808', '#00dfff', 232, 45, ''], 'airline_a_to_airline_b': ['', '', '45', '234', ''], 'airline_b_to_airline_c': ['', '', '234', '232', ''], 'airline_c13_to_airline_x': ['', '', '232', 'NONE', ''
], 'airline_c7_to_airline_x': ['', '', '232', 'NONE', ''], 'airline_warning': ['#000000', '#df5f00', 232, 166, ''], 'airline_c_to_airline_x': ['', '', '232', '232', ''], 'airline_c12_to_airline_x': ['', '', '232', 'NONE', ''], 'airline_y_t
o_airline_z': ['', '', '45', '234', ''], 'airline_z_to_airline_warning': ['', '', '166', '45', ''], 'airline_a': ['#080808', '#00dfff', 232, 45, ''], 'airline_b': ['#ff5f00', '#1c1c1c', 202, 234, ''], 'airline_c': ['#767676', '#080808', 24
3, 232, '']}, 'insert_paste': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_a': ['#080808', '#d78700', 232, 172, ''], 'airline_warning': ['#000000', '#df5f00', 232, 166]}, 'visual_modified': {'airline_error': ['#000000', '#9
90000', 232, 160], 'airline_warning': ['#000000', '#df5f00', 232, 166], 'airline_c': [...]}, 'insert_modified': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_warning': ['#000000', '#df5f00', 232, 166], 'airline_c': [...]}, '
inactive_modified': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_warning': ['#000000', '#df5f00', 232, 166], 'airline_c': ['#df0000', '', 160, '', '']}, 'visual': {'airline_x': ['#767676', '#080808', 243, 232, ''], 'airline
_y': ['#ff5f00', '#1c1c1c', 202, 234, ''], 'airline_z': ['#080808', '#dfdf00', 232, 184, ''], 'airline_error': ['#000000', '#990000', 232, 160], 'airline_a': ['#080808', '#dfdf00', 232, 184, ''], 'airline_b': ['#ff5f00', '#1c1c1c', 202, 23
4, ''], 'airline_c': ['#767676', '#080808', 243, 232, ''], 'airline_warning': ['#000000', '#df5f00', 232, 166]}, 'replace_modified': {'airline_error': ['#000000', '#990000', 232, 160], 'airline_warning': ['#000000', '#df5f00', 232, 166], '
airline_c': [...]}, 'insert': {'airline_x': ['#767676', '#080808', 243, 232, ''], 'airline_y': ['#ff5f00', '#1c1c1c', 202, 234, ''], 'airline_z': ['#080808', '#5fff00', 232, 82, ''], 'airline_error': ['#000000', '#990000', 232, 160], 'airl
ine_a': ['#080808', '#5fff00', 232, 82, ''], 'airline_b': ['#ff5f00', '#1c1c1c', 202, 234, ''], 'airline_c': ['#767676', '#080808', 243, 232, ''], 'airline_warning': ['#000000', '#df5f00', 232, 166]}, 'accents': {'orange': ['#df5f00', '',
166, ''], 'bold': ['', '', '', '', 'bold'], 'blue': ['#005fff', '', 27, ''], 'green': ['#008700', '', 22, ''], 'purple': ['#af00df', '', 128, ''], 'none': ['', '', '', '', ''], 'airline_error': ['#000000', '#990000', 232, 160], 'italic': [
'', '', '', '', 'italic'], 'yellow': ['#dfff00', '', 190, ''], 'airline_warning': ['#000000', '#df5f00', 232, 166], 'red': ['#ff0000', '', 160, '']}}
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 7: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 8: endfor
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 1: for mode in keys(a:palette)
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 5: if !has_key(a:palette[mode], 'airline_error')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 7: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 8: endfor
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 1: for mode in keys(a:palette)
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 5: if !has_key(a:palette[mode], 'airline_error')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 7: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 8: endfor
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 1: for mode in keys(a:palette)
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>echo mode
insert_modified
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 5: if !has_key(a:palette[mode], 'airline_error')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 7: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 8: endfor
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 1: for mode in keys(a:palette)
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 2: if !has_key(a:palette[mode], 'airline_warning')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 4: endif
>bt
  3 function <SNR>77_airline_theme[2]
  2 airline#switch_theme[14]
  1 airline#load_theme[6]
->0 airline#themes#patch
line 4: endif
>finish
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[6]..airline#themes#patch
line 32: End of function
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 8: if exists('g:airline_theme_patch_func')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 11: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 13: call airline#highlighter#load_theme()
>s
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 1: if pumvisible()
>
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 3: endif
>
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 4: for winnr in filter(range(1, winnr('$')), 'v:val != winnr()')
>
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 5: call airline#highlighter#highlight_modified_inactive(winbufnr(winnr))
>echo winnr
1
>echo winnr()
2
>echo winnr
1
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 6: endfor
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 4: for winnr in filter(range(1, winnr('$')), 'v:val != winnr()')
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 6: endfor
>echo winnr('$')
2
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 7: call airline#highlighter#highlight(['inactive'])
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 8: if getbufvar( bufnr('%'), '&modified'  )
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 10: else
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 11: call airline#highlighter#highlight(['normal'])
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 12: endif
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme[13]..airline#highlighter#load_theme
line 12: End of function
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 14: call airline#extensions#load_theme()
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 15: call airline#update_statusline()
>n
function <SNR>77_airline_theme[2]..airline#switch_theme[14]..airline#load_theme
line 15: End of function
>n
function <SNR>77_airline_theme[2]..airline#switch_theme
line 16: doautocmd User AirlineAfterTheme
>n
function <SNR>77_airline_theme[2]..airline#switch_theme
line 19: call airline#check_mode(winnr())
>n
function <SNR>77_airline_theme[2]..airline#switch_theme
line 19: End of function
>n
function <SNR>77_airline_theme
line 3: else
>n
function <SNR>77_airline_theme
line 5: End of function

**Comment by chrisbra** [comment]
so it looks like it does actually load your theme simple

**Comment by chrisbra** [comment]
is that perhaps the same name as you have currently loaded?

**Comment by viralshah** [comment]
Nothing happens even if I load other themes: luna etc.

**Comment by chrisbra** [comment]
Can you show something like `:hi airline_a` in a non-modified, active buffer` before and afterwards please?

**Comment by viralshah** [comment]
before:
```
:hi airline_a
airline_a      xxx ctermfg=232 ctermbg=45 guifg=#080808 guibg=#00dfff
```

`:AirlineTheme luna`

after:
```
:hi airline_a
airline_a      xxx ctermfg=231 ctermbg=36 guifg=#ffffff guibg=#005252

```

**Comment by chrisbra** [comment]
so the colors do actually change. Is the "xxx" actually displayed in a different color? If you do it manually:
```
:hi foobar ctermfg=232 ctermbg=45 guifg=#080808 guibg=#00dfff
:hi foobar
:hi foobar ctermfg=231 ctermbg=36 guifg=#ffffff guibg=#005252
:hi foobar
```
does that change the color when displaying the highlight group? And just to make sure, `:AirlineRefresh` does not change anything after changing the theme? What about `:AirlineToggle` and then again `:AirlineToggle`?

**Comment by viralshah** [comment]
So `ctermfg=232 ctermbg=45 guifg=#080808 guibg=#00dfff` and `ctermfg=231 ctermbg=36 guifg=#ffffff guibg=#005252` were close so I couldn't tell the difference.
That got me thinking. I use vim inside of tmux. This interferes with the number of colors available.
`tput colors` outputs 8 on the terminal.
Looking at the discussion [here](http://unix.stackexchange.com/questions/118806/tmux-term-and-256-colours-support) and adding the line `set -g default-terminal "screen-256color"` in my `tmux.conf`, fixes the issue when I open vim.
Yay! Issue closed and hopefully this is useful to someone else too.
Thanks a lot for you help in debugging.

**Comment by chrisbra** [comment]
closing this then.
