### ISSUE TITLE
Duplicate help tag g:airline_base16_improved_contrast

### ISSUE THREAD

**Issue by dnebauer** [vim-airline/vim-airline-themes#67]
Prior to commit 6565b2 on 18 December 2016 the help tag `g:airline_base16_improved_contrast` already existed in `airline-themes.txt`. That commit introduced the same help tag a second time. The duplicate tags are on lines 154 and 177 of the current version of `airline-themes.txt`.

**Comment by LovingYoung** [comment]
The same problem. I deleted the second tag and it worked.
Waiting for updates to fix it.
