### ISSUE TITLE
jellybeans theme statusbar is red after update

### ISSUE THREAD

**Issue by craigp** [vim-airline/vim-airline-themes#8]
<img width="875" alt="screenshot 2016-02-11 13 58 16" src="https://cloud.githubusercontent.com/assets/9042/12975812/96648622-d0c7-11e5-8542-dcecbaf10237.png">

**Comment by chrisbra** [comment]
Please update, this should have been fixed with the last PR.

**Comment by craigp** [comment]
Thanks, all sorted
