### ISSUE TITLE
Papercolor theme doesn't change color with modes

### ISSUE THREAD

**Issue by elamperti** [vim-airline/vim-airline-themes#80]
Using the `papercolor` theme, changing from normal to insert/visual/replace won't change the airline color. It would be great if it did! 

Meanwhile I'm using the `cool` theme, which works as expected.

**Comment by chrisbra** [comment]
I actually like it, that the colors are not switched often and I suspect, it can even help with slow performance problems that are seen sometimes (vim-airline/vim-airline#1026). However, If you like to contribute a change, that is available via a configuration variable, I am not against it.

**Comment by golergka** [comment]
Just switched to papercolor, airline colors are changing just fine.

**Comment by chrisbra** [comment]
it doesn't change color, when changing modes.

**Comment by golergka** [comment]
Strange. Definitely changes for me when I go into and back form insert and visual modes. But I changed to papercolor using a command after vim had already started, not by modifying vimrc and relaunching vim - may be it could be related?

**Comment by chrisbra** [comment]
is this still a problem?
