### ISSUE TITLE
missing theme 'dark'

### ISSUE THREAD

**Issue by anthraxx** [vim-airline/vim-airline-themes#81]
How exactly am I supposed to get the very same theme as I was used to have when setting g:airline_theme to "dark" before? it yells me an error that themes have been migrated here, but i have this repo installed. the regular theme i'm using is 'molokai' but if i use that as airline_theme i get a totally different thing then before the split.
Please help, i want my theme back :stuck_out_tongue_closed_eyes: 

This is how it looked, and i can't find any option to get it back like this:
![2017-03-21-130121_1920x1080_scrot](https://cloud.githubusercontent.com/assets/203012/24146643/d818c2a6-0e36-11e7-9ac8-ece516a06f9b.png)

**Comment by chrisbra** [comment]
I believe this is the default dark theme.

**Comment by anthraxx** [comment]
It should be, but it doesn't work. when i roll back vim-airline-theme to old 516454c then it works.

**Comment by chrisbra** [comment]
what do you mean it doesn't work? the default dark theme is available in the vim-airline repository. What exactly are you doing?

**Comment by anthraxx** [comment]
well it automatically selects some bright thingie if i remove the theme line, and if i have the theme setting with value "dark" in the .vimrc then i get error messages.

**Comment by anthraxx** [comment]
Ok I found out: the latest release is not compatible with the newest airline-theme git version.
Would it be possible to tag a new vim-airline release? That would resolve my issue as the distro package would get updated :yum:

**Comment by chrisbra** [comment]
well by default airline tries to use a theme that matches your colorscheme. If you don't want that, you should set the [g:airline_theme variable](https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L86-L88)

**Comment by chrisbra** [comment]
> the latest release is not compatible with the newest airline-theme git version

That should still work. What errors are you seeing?

**Comment by anthraxx** [comment]
the vim-airline release tarball (over a year ago) does not have the dark.vim theme inside but it was removed from the vim-airline-themes-git. I get the error message: "Count not resolve airline theme 'dark'. Themes have been migrated......"
However it works when using vim-airline HEAD instead of release

**Comment by anthraxx** [comment]
@chrisbra i was digging a bit deeper and it may be a packaging issue with the way vim-airline was packaged for the distribution. Let me check and sorry if that is the case. Will close this when validated and owe you a beer :yum:

**Comment by anthraxx** [comment]
@chartoin yes, it is indeed a packaging issue and it works. the dark theme was forcefully removed, i repoted it to the packager. Thanks again for this great plugin

PS: either way, a release can't hurt as its a year old :smile_cat:
