### ISSUE TITLE
Fonts partly displayed wrong

### ISSUE THREAD

**Issue by CodingJonas** [vim-airline/vim-airline-themes#83]
I installed the powerline fonts and tried to make the right settings in my [vimrc](https://github.com/CodingJonas/dotfiles/blob/master/.vimrc) (did I miss something)?

You can see, every symbol is displayed properly in the help file, but not in the real powerline.

![screenshot from 2017-03-24 10-49-04](https://cloud.githubusercontent.com/assets/15234763/24396514/c273db4e-13a3-11e7-8b51-6c2a6f6f4d34.png)

What is the problem here?

**Comment by chrisbra** [comment]
you screenshot is not working.

**Comment by chrisbra** [comment]
looks like a problem with your terminal.
