### ISSUE TITLE
missing solarized dark theme

### ISSUE THREAD

**Issue by djdanielsson** [vim-airline/vim-airline-themes#86]
I noticed that solarized dark theme is missing from the themes folder and I would love to have that as an option again.

**Comment by chrisbra** [comment]
What do you mean with missing? Was this ever there?

**Comment by djdanielsson** [comment]
you show it as an option right here https://github.com/vim-airline/vim-airline/wiki/Screenshots#solarized-dark so I would have thought so

**Comment by chrisbra** [comment]
Isn't that just the normal solarized theme with bg=dark?

**Comment by djdanielsson** [comment]
I don't know how to set it as that, but I would like to have my airline look like that, I tried :AirlineTheme solarized dark and that does not work, I assumed that the name you had listed would be the name of the theme like all the others.

**Comment by chrisbra** [comment]
That has nothing to do with `:AirlineThemes` You need to install the solarized colorscheme. Then do `:colors solarized` and possibly also `:set bg=dark`

**Comment by djdanielsson** [comment]
![myscreenshot](https://cloud.githubusercontent.com/assets/15205330/25556096/39e39c9c-2cbc-11e7-8057-5cf8e0ac35b7.png)
that would only change the vim background itself but not airline. I already have this set, I am trying to make airline match.

**Comment by djdanielsson** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/15205330/25556233/c0a85eaa-2cbe-11e7-95cc-ff1344f00f09.png)
I tried to do exactly what you said after removing all my vimrc information except what was needed for airline and got this, I still think it looks more washed out then your screen shot but maybe that is just me and its actually working. So I'm sorry for wasting your time, thank you for all the work you have done, I love airline.

**Comment by chrisbra** [comment]
It could be, that the theme has been changed slightly in the past, so the screenshot does not match the theme file anymore. Also, the solarized theme comes with some configuration variables see [here](https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/solarized.vim#L7-L10) Also check the [documentation](https://github.com/vim-airline/vim-airline-themes/blob/master/doc/airline-themes.txt#L126). 

However, if you still think some colors need adjustments, feel free to propose some changes. If they are properly documented, I won't refuse to include it.

**Comment by djdanielsson** [comment]
I took a look at everything again, I think it is probably correct, but for myself I decided to change some colors so it looks more to what I was expecting. Thanks again for all your hard work.
