### ISSUE TITLE
missing of instructions for installation

### ISSUE THREAD

**Issue by nicolas33** [vim-airline/vim-airline-themes#9]
I'm expecting README to have the intructions to install the themes.

**Comment by chrisbra** [comment]
What kind of instructions are you missing?

**Comment by nicolas33** [comment]
The steps to intall the themes.

**Comment by mhartington** [comment]
If you've been able to install any vim plugin before, this shouldn't be anything new.

https://github.com/vim-airline/vim-airline-themes#installation

**Comment by nicolas33** [comment]
Thanks! I know how to install vim plugins but vim-airline-themes looks more like a **vim-airline** plugin. At least, this is what the previous version of the README suggests.
I'm sorry my point was not clear enough.
Thanks again!
