### ISSUE TITLE
AirlineTheme not an editor command

### ISSUE THREAD

**Issue by plexigras** [vim-airline/vim-airline-themes#93]
i added `Plugin 'vim-airline/vim-airline-themes'` and ran `:PluginInstall!`

~/.vimrc
---
```vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()

filetype plugin indent on
syntax on

set wildmenu
set ruler
set number
set backspace=indent,eol,start
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.png,.jpg
set mouse=a
set clipboard=unnamedplus

```

**Comment by chrisbra** [comment]
You need the vim-airline repository of course.

**Comment by plexigras** [comment]
@chrisbra i have the repository it gets installed into `~/.vim/bundle/vim-airline-themes` when runing `:PluginInstall`

**Comment by chrisbra** [comment]
According to your information you only have the themes repository, but you need the main vim-airline repository as well.

**Comment by plexigras** [comment]
oh ok thx @chrisbra.

i suppose adding that to the readme could help in the future.

**Comment by chrisbra** [comment]
okay, will do then

**Comment by chrisbra** [comment]
[done](https://github.com/vim-airline/vim-airline-themes/commit/7865fd8ba435edd01ff7b59de06a9be73e01950d)
