### ISSUE TITLE
How to change text colors?

### ISSUE THREAD

**Issue by iamsubhranil** [vim-airline/vim-airline-themes#95]
Hey, how do I change the color of NORMAL and line count texts(foreground color)?
Also, how to convert 16 colors to 256 colorspace?
i.e. I'm currently doing
let s:cterm01 = "00"
how to change it do
let s:cterm01 = 234(or whatever equivalent number is)?

**Comment by chrisbra** [comment]
I don't understand. You can change the normal highlighting via `:hi Normal ...` The colors of the statusline are pretty much defined by the airline-theme you are using.  I don't understand what you mean with `:let s:cterm01...`

**Comment by iamsubhranil** [comment]
I'm talking about the themes, where I'm defining colors. I'm trying to port base16 darktooth, but enable to set the NORMAL and line count text colors from inside the base16_darktooth.vim file. How to do that?

**Comment by chrisbra** [comment]
the NORMAL should be highlighting group airline_a (bold) and the wordcount is airline_z highlighting group.

**Comment by iamsubhranil** [comment]
Can you link a theme as an example?
