### ISSUE TITLE
Distinguished inactive pane title too low-contrast

### ISSUE THREAD

**Issue by thallada** [vim-airline/vim-airline-themes#97]
I can barely read the inactive pane titles. I tried editing the theme myself but it only changed the colors of active pane titles. Can someone help me?

![screenshot-20170719144436-324x21](https://user-images.githubusercontent.com/1505923/28383939-d627789e-6c90-11e7-8337-48d8c5a91546.png)

**Comment by chrisbra** [comment]
have you tried using a different theme? With what theme does that happen? And what gui?

**Comment by thallada** [comment]
This is in the terminal (so it uses the cterm colors). It happens with the default dark theme too, but not the jellybeans theme. I managed to steal the inactive part of the jellybeans theme and put that in the distinguished theme and it looks better now. Since this only seems to happen to me I guess I won't make a PR for it though.
