### ISSUE TITLE
Powerline symbols for badwolf theme in GUI mode are all white

### ISSUE THREAD

**Issue by s0ph0s-2** [vim-airline/vim-airline-themes#99]
I'd like to use [VimR](https://github.com/qvacua/vimr) as my default neovim interface. However, when using the `badwolf` theme, all of the powerline 'arrow' symbols are white, which is not the case when running neovim in a terminal. The issue is pictured below (VimR is on top, exhibiting the incorrect colors, iTerm 2 is on the bottom, showing the proper behavior).

![powerline-error](https://user-images.githubusercontent.com/20545101/28736068-34cbc900-73b6-11e7-97b1-4298712c393c.png)

**Comment by chrisbra** [comment]
is this another issue with `:echo has("gui_running")`?

**Comment by s0ph0s-2** [comment]
Hmm. I thought I investigated that and determined that it was not. However, I just checked again, and both `:echo has("gui")` and `:echo has("gui_running")` both report `0`. That indicates to me that this is not, in fact, an issue with vim-airline-themes, but instead should be raised on VimR's issue tracker. Sorry about the extraneous issue!
